### ISSUE TITLE
better description of LP_PATH_KEEP 

### ISSUE THREAD

**Issue by Cougar** [nojhan/liquidprompt#170]
Hi,

I'm not sure is it a bug, a feature or just a bad description of this config variable. In default setup it is 2 but in the prompt only first directory is shown.

if the directory is "/home/cougar/..."
then the beginning with LP_PATH_KEEP=2 is "/home"

Of course "/" is the first directory and "cougar" is the second one but this does not look very logical as long the first directory is always "/" and you can't get rid of that ;-)

I suggest to not count first "/" as a one directory

**Comment by Rycieos** [comment]
First, I disagree, and think that `/` is a directory. This makes `LP_PATH_KEEP=2` display like this:
```
/tmp … dir
~/dir … dir
```
Which looks more consistent to me between a directory in the root and one in the user's home directory.
And this is how Liquidprompt has been working for a while now, so it shouldn't be changed now.

But the point of this issue was to document it better, which I have now done in [v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1):
https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/config.html#LP_PATH_KEEP
