### ISSUE TITLE
Extremely slow with nothing enabled

### ISSUE THREAD

**Issue by darkpixel** [nojhan/liquidprompt#226]
I tried to narrow down what was slowing the prompt down, so I set my .liquidpromptrc file to contain:

```
LP_ENABLE_PERM=0                                                                
LP_ENABLE_SHORTEN_PATH=0                                                        
LP_ENABLE_PROXY=0                                                               
LP_ENABLE_JOBS=0                                                                
LP_ENABLE_LOAD=0                                                                
LP_ENABLE_BATT=0                                                                
LP_ENABLE_GIT=0                                                                 
LP_ENABLE_SVN=0                                                                 
LP_ENABLE_HG=0                                                                  
LP_ENABLE_BZR=0                                                                 
LP_ENABLE_FOSSIL=0                                                              
LP_ENABLE_VCS_ROOT=0                                                            
LP_ENABLE_TITLE=0                                                               
LP_ENABLE_SCREEN_TITLE=0                                                        
LP_ENABLE_SSH_COLORS=0                                                             
LP_ENABLE_TIME=0                                                                   
LP_TIME_ANALOG=0                                                                   
```

It still takes about 2 seconds to display the bash prompt with everything disabled.

(Edited .liquidpromptrc, saved, opened a new bash prompt, sourced the file and tested)

Anything else I can check/do to troubleshoot?

**Comment by lemire** [comment]
> By the way, the things which slow liquidprompt the most are temp, load and jobs.

Git is certainly not free. For sizeable repositories, I have seen massive delays.

**Comment by mpeng-okta** [comment]
Would really appreciate some help with this as well. I'm on couple-days-old MacBook Pro 16" (2019) on MacOS Catalina with a 2.3 GHz 8-Core Intel Core i9, and in-repo the wait time is out of control.

From user home:
```
real	0m0.001s
user	0m0.001s
sys	0m0.000s
```

In repo (showing the flags now as well):
```
$ set | grep ^LP_ENABLE_
LP_ENABLE_BATT=0
LP_ENABLE_BZR=0
LP_ENABLE_COLOR=1
LP_ENABLE_DETACHED_SESSIONS=0
LP_ENABLE_DIRSTACK=0
LP_ENABLE_ERROR=1
LP_ENABLE_FOSSIL=0
LP_ENABLE_FQDN=0
LP_ENABLE_GIT=1
LP_ENABLE_HG=0
LP_ENABLE_JOBS=0
LP_ENABLE_LOAD=0
LP_ENABLE_PERM=1
LP_ENABLE_PROXY=1
LP_ENABLE_RUNTIME=0
LP_ENABLE_RUNTIME_BELL=0
LP_ENABLE_SCLS=1
LP_ENABLE_SCREEN_TITLE=0
LP_ENABLE_SHORTEN_PATH=1
LP_ENABLE_SSH_COLORS=0
LP_ENABLE_SUDO=0
LP_ENABLE_SVN=1
LP_ENABLE_TEMP=0
LP_ENABLE_TIME=0
LP_ENABLE_TITLE=0
LP_ENABLE_VCSH=1
LP_ENABLE_VCS_ROOT=0
LP_ENABLE_VIRTUALENV=1

real	0m9.994s
user	0m0.519s
sys	1m47.722s
```

The strange thing is, in the exact same repo and commit on an older MBP on also MacOS Catalina, just 15" (2018) with 2.6 GHz 6-core Intel Core i7, with essentially the same settings, the speed is somehow >3x faster. It's still 2 to 3 s which is not great but livable, but see (this is called from in repo):
```
± set | grep ^LP_ENABLE_
LP_ENABLE_BATT=0
LP_ENABLE_BZR=0
LP_ENABLE_FOSSIL=0
LP_ENABLE_FQDN=0
LP_ENABLE_GIT=1
LP_ENABLE_HG=0
LP_ENABLE_JOBS=0
LP_ENABLE_LOAD=0
LP_ENABLE_PERM=1
LP_ENABLE_PROXY=1
LP_ENABLE_RUNTIME=0
LP_ENABLE_SCLS=1
LP_ENABLE_SCREEN_TITLE=0
LP_ENABLE_SHORTEN_PATH=1
LP_ENABLE_SSH_COLORS=0
LP_ENABLE_SUDO=0
LP_ENABLE_SVN=1
LP_ENABLE_TEMP=0
LP_ENABLE_TIME=0
LP_ENABLE_TITLE=0
LP_ENABLE_VCSH=1
LP_ENABLE_VCS_ROOT=0
LP_ENABLE_VIRTUALENV=1
real	0m2.685s
user	0m0.703s
sys	0m11.436s
```

The sys runtime is somehow an _order of magnitude_ higher on the new machine, and I have no idea why that's the case. Other than having a newer version of liquidprompt on the new machine, but it would seem very strange to get a 3x real slowdown with the same flags, from what I can tell... Any help would be appreciated since I've already deactivated all the problematic flags that I can see.

**Comment by Rycieos** [comment]
@mpeng-okta can you add some info like OS version, shell version, and Git version?

How long does this command take?
```bash
time for i in {1..10}; do git status >/dev/null 2>&1; done
```
For me, it takes
```
real    0m1.181s
user    0m0.592s
sys     0m0.764s
```
which is typical. Also try `time _lp_vcs_details_color` and post the output.

If it is longer for you, that seems to point at a Git problem. My guesses right now are you are reading a network repo, or running a bad version of Git somehow.

**Comment by mpeng-okta** [comment]
Sure thing, I'm on:
- OS version: `10.15.7 (19H524)`
- Shell version: `GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin19.6.0)`
- Git version: `git version 2.31.0`

Here's the git status output timing:
```time for i in {1..10}; do git status >/dev/null 2>&1; done

real	0m50.275s
user	0m4.084s
sys	8m20.987s
```

Here's the _lp_vcs_details_color timing:
```
 time _lp_vcs_details_color

real	0m10.455s
user	0m0.515s
sys	1m54.964s
```

So yeah it does seem like there's some issue with Git, but for the life of me I can't figure it out, since it's the same repo across the computers. The other machine has git version 2.23 and and is on the same bash version.

**Comment by Rycieos** [comment]
Yeah, that's a Git problem. Do you notice slow Git response when using Git? Do you get better times in a brand new, empty repo?

What did you use to install Git? MacOS dev tools, or Homebrew?

**Comment by mpeng-okta** [comment]
I do notice slow Git response when using it. I do get better times in a different (smaller) repo, but it basically scales w.r.t. the other computer, i.e. a 3x slowdown compared to that machine.

I believe git was installed through Homebrew (`brew list` does have git show up in the list). 
 
Realized I did clone the repo via the GitHub CLI as opposed to just using Git -- this is the only big difference of which I'm aware between the machines, so I'll try to use `git clone` instead of `gh clone`. Not sure if this is a non-issue though.

**Comment by mpeng-okta** [comment]
This is what fixed the issue for me:
`git config --bool core.preloadindex false`

Here's the breakdown when I run `time for i in {1..10}; do git status >/dev/null 2>&1; done`:
1. New computer core.preloadindex **true**
```
real	0m43.317s
user	0m4.243s
sys	6m30.697s
```
2. New computer core.preloadindex **false**
```
real	0m14.861s
user	0m3.622s
sys	0m11.559s
```
3. Old computer core.preloadindex **true**
```
real	0m18.762s
user	0m5.444s
sys	1m4.466s
```
4. Old computer core.preloadindex **false**
```
real	0m16.495s
user	0m5.368s
sys	0m11.543s
```

This basically puts my new and old machines pretty much at the same real time (I guess git is mostly fs-based and it's not like the new SSD has a big improvement in performance).

Super strange, but it looks like having this git flag set to true indeed means a 3x real performance loss on the new machine, and a staggering >30x performance loss w.r.t. to CPU time.

Somehow, there's no real performance loss on the old device, but there's still a >5x performance loss w.r.t. CPU time.

Anyway, thanks so much for your help, and maybe this could help someone else when they're Googling around.
