### ISSUE TITLE
Allow command timeout

### ISSUE THREAD

**Issue by bbannier** [nojhan/liquidprompt#243]
Hi,

let me say first that I like liquidprompt a lot.

I was wondering if you could consider adding the possibility to timeout
commands. I am think this would be most useful when working with disks mounted
over the network (e.g. AFS, NFS, SSHFS). I often find myself manually killing
calls to e.g. `git status` which take forever when working on large
repositories sitting in such filesystems.

For the implementation I could imagine some infrastructure that makes sure all
commands doing disk access being wrapped in a function which ensures that they
won't take more than some configured time. One could even use `timeout` which
comes e.g. with recent coreutils and fallback to a simple pass-through
function which doesn't time out in case no `timeout` is found.

Would you consider such a change?

**Comment by pjvandehaar** [comment]
For reference, here's a way to use `timeout` (or `gtimeout` on OSX with Homebrew) with the `git` commands.  It's messy and has no fallback.  https://github.com/pjvandehaar/dotfiles/blob/ec2707/prompt_prompt.sh#L31

**Comment by Rycieos** [comment]
I don't think this is a good idea. Timeouts for shell commands isn't something designed into the language, and is messy at best. This is the best resource I have found on the topic: http://mywiki.wooledge.org/BashFAQ/068

If `git` or similar binaries had `--timeout` flags, then maybe I would consider this. But since we would have to hack it, I don't think it's a good idea.

Instead, use the `$LP_DISABLED_VCS_PATH` variable to disable large and/or slow repositories.
