### ISSUE TITLE
feature: option to show only the last part of the directory name

### ISSUE THREAD

**Issue by dolmen** [nojhan/liquidprompt#256]
Add a variation of `LP_ENABLE_SHORTEN_PATH` to only show the last part of the directory name.

See comment in [#219](https://github.com/nojhan/liquidprompt/issues/219#issuecomment-30831232) for ideas.

**Comment by dolmen** [comment]
This feature is already implemented: LP_PATH_KEEP=-1
But it has to be documented.

**Comment by Rycieos** [comment]
First documented in v2.0.0-beta.1 [here](https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/config.html#LP_PATH_KEEP).

**Comment by Rycieos** [comment]
This feature is still supported, but it has been changed in [v2.0.0-rc.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-rc.1) to have a different selection mechanism.

[`LP_PATH_KEEP`](https://liquidprompt.readthedocs.io/en/v2.0.0-rc.1/config.html#LP_PATH_KEEP) has a note on it that the `-1` value is deprecated, since now [`LP_PATH_METHOD`](https://liquidprompt.readthedocs.io/en/v2.0.0-rc.1/config.html#LP_PATH_METHOD) exists, and with a value of `truncate_to_last_dir` it will only show the last directory on the path.
