### ISSUE TITLE
Show sudo credential status

### ISSUE THREAD

**Issue by dolmen** [nojhan/liquidprompt#335]
When you run `sudo`, the credentials may be saved by `sudo` for that shell. This means that any command running from that shell will be able to use those credentials. So it is safer for the user to remember to remove those credentials once he doesn't need it anymore. Liquid Prompt is a good place to signal the user that `sudo` credentials are active.

To check `sudo` credentials (returns 0 if credentials are cached, 1 if not):

```
sudo -n /bin/true 2> /dev/null
```

To expire your credentials:

```
sudo -K
```

To renew your credentials for 15 minutes:

```
sudo -v
```

**Comment by jsuter1** [comment]
Can LP_ENABLE_SUDO be changed to default to 0? If the user is not permitted to run sudo commands, it will trigger a sudo event:
`Jan 20 15:30:25 xxxx sudo:   xxxx : user NOT in sudoers ; TTY=pts/57 ; PWD=/home/xxxx ; USER=root ; COMMAND=/bin/true`

I had a customer trigger 50+ sudo alerts over the course of the day due to this.
