### ISSUE TITLE
VCSH should print $VCSH_DIRECTORY

### ISSUE THREAD

**Issue by brianmay** [nojhan/liquidprompt#363]
Not sure if this is correct, but was thinking something along the lines of:

```
diff --git a/liquidprompt b/liquidprompt
index a801407..2f17148 100755
--- a/liquidprompt
+++ b/liquidprompt
@@ -1444,7 +1444,7 @@ _lp_smart_mark()
     case "$LP_VCS_TYPE" in
     git)      mark="$LP_MARK_GIT"             ;;
     git-svn)  mark="$LP_MARK_GIT$LP_MARK_SVN" ;;
-    git-vcsh) mark="$LP_MARK_VCSH$LP_MARK_GIT$LP_MARK_VCSH";;
+    git-vcsh) mark="$LP_MARK_VCSH$VCSH_DIRECTORY:$LP_MARK_GIT$LP_MARK_VCSH";;
     hg)       mark="$LP_MARK_HG"              ;;
     svn)      mark="$LP_MARK_SVN"             ;;
     fossil)   mark="$LP_MARK_FOSSIL"          ;;
```

Now I get:

```
1d [brian:~] % vcsh enter zsh
1d [brian:~] master(+1/-34) |zsh:±| 
```

**Comment by dolmen** [comment]
I need feedback from users of the vcsh feature.

@clneagu, @RichiH: what do you think?

**Comment by tribut** [comment]
I agree that it would be really helpful if `$VCSH_DIRECTORY` was shown for vcsh.

**Comment by DancingQuanta** [comment]
Yes I second this feature. Entering a VCSH environment without showing that you entered is a bit confusing, only indicator is that `master` for git shows up. Liquidprompt already shows virtualenvs, so vcsh should be treated similarly.

**Comment by Rycieos** [comment]
Stumbled across this issue again while trying to understand how VCSH works. Anyone want to help me understand this?

If one `cd`s into a directory with a VCSH repo, not only will it looks like a Git repo, but `$VCSH_DIRECTORY` will be set automatically? If that is the case, then Liquidprompt's job is easy, but an environment variable appearing from nowhere seems too good to be true.

**Comment by brianmay** [comment]
@Rycieos 

You type in something like:

```
vcsh enter common
```

vcsh will setup various environment variables and enter a new shell. Such as `VCSH_COMMAND`, `VCSH_DIRECTORY` and `VCSH_REPO_NAME`. It also confreres git to use the non-standard git directory.

```
brian@canidae:~$ vcsh enter common
brian@canidae:~$ echo $VCSH_COMMAND
enter
brian@canidae:~$ echo $VCSH_DIRECTORY
common
brian@canidae:~$ echo $VCSH_REPO_NAME
common
brian@canidae:~$ echo $GIT_DIR 
/home/brian/.config/vcsh/repo.d/common.git
```

Similar to commands like virtualenv, pyenv, and asdf (can't remember if liquidprompt supports any of these).

**Comment by Rycieos** [comment]
@brianmay thanks! So you don't `cd` into a VCSH directory, you enabled a VCSH context.

In that case, I understand your request. Your current directory would not help ID the repo you are in, but `$VCSH_DIRECTORY` would.

I'm not sold on doing the check in `_lp_smart_mark()`, since it is a theme function, but as @DancingQuanta suggested, since it is more like a development environment, it should probably be added as data source like that, and then displayed in the default theme between the VCS section and the prompt mark. Or maybe even in the prompt mark like you suggested. But it needs its own data function for sure. And then could be disabled with `$LP_ENABLE_VCSH` (which I just removed because it did nothing, but we can add it back).

If anyone wants to take a stab at a PR for this, feel free. Otherwise I'm leaving this on the plans for v2.1 for myself to work on.
