### ISSUE TITLE
`C-x C-e` echos `_lp_reset_runtime`

### ISSUE THREAD

**Issue by pjvandehaar** [nojhan/liquidprompt#400]
```
[pjvandehaar@MBA:~/liquidprompt] myb ±  echo hi <C-x C-e>
echo hi
_lp_reset_runtime
hi
```

**Comment by dolmen** [comment]
Which shell (and what version)?

**Comment by dolmen** [comment]
Verify this still happens with the code on the `develop` branch.

**Comment by pjvandehaar** [comment]
It happens on both `BASH_VERSION=4.3.42(1)-release` from `http://ftpmirror.gnu.org/bash/bash-4.3.tar.gz` and `BASH_VERSION=3.2.57(1)-release`, the OSX 10.11.1 default.  I'm on the branch `develop`.  Do you get different behavior?

**Comment by dolmen** [comment]
I can reproduce.
This seems related to our use of `trap DEBUG`.
I don't know what to do. I think this is a bash issue. I'll try to write a simple test case.

**Comment by pjvandehaar** [comment]
I agree– it's probably not fixable.  I ran into it in another project that uses `trap DEBUG`. We could ask the folks at StackOverflow– they seem to like obscure questions.

**Comment by tomvanderlee** [comment]
I cannot reproduce this.

Bash:

    [Thu Dec 03][13:13:19]tom on MrMeeseeks
    ~ $ echo $BASH_VERSION
    4.3.42(1)-release`

Xterm:

    [Thu Dec 03][13:13:45]tom on MrMeeseeks
    ~ $ xterm -v
    XTerm(320)

Linux:

    [Thu Dec 03][13:14:20]tom on MrMeeseeks
    ~ $ uname -a
    Linux MrMeeseeks 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux

**Comment by pjvandehaar** [comment]
I see `LP_ENABLE_RUNTIME=0` at <https://github.com/tomvanderlee/dotfiles/blob/master/liquidprompt/.liquidpromptrc#L105>.  You enabled it to try this, right?

**Comment by tomvanderlee** [comment]
Well I did not, my bad.

Enabled it and I can confirm the bug.

**Comment by globalundo** [comment]
Can confirm that the bug is still present, see [demo](https://asciinema.org/a/3ypdhmnlur5g4jhw9ssuwl92j)

**Comment by izissise** [comment]
Hello, I'm still having a similar issue where the runtime isn't reset between commands.

**Comment by Rycieos** [comment]
@izissise, your issue is probably unrelated. See the [Prompt timing section](https://github.com/nojhan/liquidprompt/wiki/FAQ#prompt-timing-isnt-working) of the FAQ, and open a separate issue if that doesn't fix it.

I can still confirm this, I'll do some digging. I also tried to reproduce it with zsh, to no luck. First you [have to enable it](https://unix.stackexchange.com/a/34251) (not on by default). It seems that in zsh when you exit the editor drops you back on the command line, where bash runs the command. Maybe that is tied to the cause.

**Comment by Rycieos** [comment]
Honestly this feature seems pretty dangerous. As [others elsewhere have pointed out](https://unix.stackexchange.com/questions/85391/where-is-the-bash-feature-to-open-a-command-in-editor-documented#comment1039008_85393), if you exit the editor, Bash will just run the command as is. Could do something destructive with that. But that is beside the point.

I found quite a bit of discussion on this, actually. But strangely, it is all very recent. And some of seems to suggest that this bug was added in version 5.0. I don't buy that, as @pjvandehaar and I have shown that it's a problem from 3.2 through 4.4. Anyway, here is a dump of what I have found:

https://lists.gnu.org/archive/html/bug-bash/2020-04/msg00016.html
https://gitlab.com/gnachman/iterm2/-/issues/8808
https://github.com/rcaloras/bash-preexec/issues/108
https://unix.stackexchange.com/q/583927
https://stackoverflow.com/q/38888022/8338372

The consensus seems to be that it is a bug in Bash. There also doesn't seem to be a decent workaround for this, and since it is something that doesn't come up very often, I'm not inclined to complicate this more than I need to. Especially since you can reproduce this with a default Bash setup:
```bash
$ trap 'echo trap' DEBUG
$ echo foobar
trap
foobar
$ echo foobar C-xC-e
echo foobar
echo trap
trap
foobar
$
```
