### ISSUE TITLE
Git repo data doesn't appear after creating a new repo

### ISSUE THREAD

**Issue by austinglaser** [nojhan/liquidprompt#466]
Shell: bash
Operating system: kubuntu 16.04 w/ i3 wm
Liquid Prompt version (tag, commit): v1.11, 488bb5975db9fa8be0b795019f0b6d99ec792f50

When creating a new git repository, the repo information doesn't appear until you `cd` out and back in.

![Liquidprompt git issue](http://i.imgur.com/Uwr5lSZ.png)

**Comment by dolmen** [comment]
We are in fact caching some information about the current directory. And there is no lightweight solution for detecting when the current directory has been suddenly transformed into a VCS managed directory. We decided that this is a sufficiently rare case and that the problem is quickly seen (just after `git init`) and the fix is obvious (you found it: `cd ..`, then `cd -`).

**Comment by nojhan** [comment]
Documentation fixed.
