### ISSUE TITLE
Slow on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by ghost** [nojhan/liquidprompt#468]
Shell: bash
Operating system: Bash on Ubuntu on Windows aka Windows Subsystem for Linux (WSL) Windows 10
Liquid Prompt version (tag, commit): 1.11

Using liquidprompt in WSL is really slow. I have disabled Bazaar, FOSSIL and SVN but overall the default configuration is used.
Pressing enter at the prompt causes the prompt to return after 3-4 seconds.

Edit: I disabled the LP_ENABLE_JOBS, LP_ENABLE_LOAD and LP_ENABLE_BATT and the lag occurring between the prompt appearing after simply pressing enter is reduced to 1-2 seconds.

[liquidpromptrc.txt](https://github.com/nojhan/liquidprompt/files/478001/liquidpromptrc.txt)

**Comment by dolmen** [comment]
On bash the LP_DEBUG_TIME=1 setting will give more precise timing.

You should also disable any other setting that requires input from the hardware. I'm thinking in particular to `LP_ENABLE_TEMP` (which is about CPU/GPU temperatures).

On a more general view, I think we will not be able to do major improvements on this platform for the default LiquidPrompt configuration. For this speed issue you should complain to Microsoft.

Anyway, it would still be interesting if you could try on the same hardware+Windows to run LiquidPrompt in an Ubuntu VM in a virtual machine (such as VirtualBox) and tell us the differences of timing.

Also, I'm also the author of [angel-PS1](/dolmen/angel-PS1) (another advanced shell prompt but with a totally different architecture) and would be interested if you could benchmark it too on WSL and [report your results as an issue](/dolmen/angel-PS1/issues/new).

**Comment by nojhan** [comment]
This benchmark from Phoronix
https://www.phoronix.com/scan.php?page=article&item=windows-10-lxcore&num=6
say that WSL face some performance problems "in areas when dealing with
file-system / disk performance".

Some features of the liquidprompt heavily rely on FS I/O and LP is itself
optimized to be usable on Linux, while having tons of features. Even on
Linux, if you use it on slow FS, you will rapidly face performances
problems.

The solution may be to deactivate features relying on the FS.

**Comment by nicolaiarocci** [comment]
I am experiencing this as well. Setting LP_ENABLE_JOBS, LP_ENABLE_LOAD, LP_ENABLE_BATT and LP_ENABLE_TEMP to 0 helps, but it is still noticeably slower than with liquidprompt turned off (to the point that I disabled liquidprompt in WSL).

**Comment by markeissler** [comment]
I don't use `liquidprompt` but I am the maintainer of [GVM2](https://github.com/markeissler/gvm2), the Go enVironment Manager. __GVM2__ is also quite slow on WSL, and I suspect the problem is the frequency with which shell sub-processes are spawned.

A brief scan of `liquidprompt` reveals 125 such calls throughout the code.

Forking a process in Windows is much more expensive than it is in *nix type operating systems like macOS and Linux. FWIW, the WSL team is aware of this as described here:

[`stack ghc` painfully slow](https://github.com/Microsoft/BashOnWindows/issues/1671)

Ideally, it would be best to restructure shell scripts to avoid spawning sup-processes unnecessarily. With that said, other than noting the number of  times sub-processes are created in `liquidprompt` I haven't actually looked at these calls with an eye towards improvement but I know I'll be looking at my own project in the coming weeks to try and reduce the number of these types of calls that are made.

**Comment by dolmen** [comment]
@markeissler I know the issue and it is not fixable in LiquidPrompt. I already worked hard to reduce calls to external tools while still preserving features.
That's why I have created [The Angel's Prompt](/dolmen/angel-PS1) a long time ago. Not yet as featureful as LiquidPrompt, but it solves the core performance issues with an architecture that really reduces forks.
