### ISSUE TITLE
Set up test suite and CI

### ISSUE THREAD

**Issue by felixSchl** [nojhan/liquidprompt#469]
I am trying to land #465 but verifying it won't break existing behavior is mundane and probably incomprehensive. It would be great to set up a test suite that has the ability to test various pieces of functionality automatically. I have used https://github.com/sstephenson/bats in my personal projects with pretty good success but I am happy to hear about alternatives. Writing tests in retrospective is no fun, so I'd propose (and volunteer my time) to set up enough of a testing framework that tests can be added easily, so they can accumulate over time. What are your thoughts on this? In terms of CI, I am using travis for my personal open source projects. Whatever we choose, we can have it install all supported shells and vcs and so on and run the tests in a matrix.

**Comment by nojhan** [comment]
There is an old first attempt of automated test in the `test.sh` file,
maybe useful to gather some ideas.

**Comment by dolmen** [comment]
:+1: for bats: I like that it can output TAP. The only drawback: I see nothing about a port on zsh.
:+1: for Tavis-CI: I'm already using it for all my Perl projects (I am using it extensively for unit testing of my other shell prompt project, [angel-PS1](/dolmen/angel-PS1); see its [.travis.yaml](/dolmen/angel-PS1/blob/release/.travis.yml))

So go ahead!

For the level of testing I think we should concentrate on this level of functional test:

- setup:
    - setup an environment
    - define a liquidprompt configuration
    - run liquidprompt
- for each test:
    - run a command that changes the environment (for example: chdir)
    - run _lp_set_prompt
    - check the values of the `LP_*` and/or `PS1` variables

Testing the changes of the LP_* variables seems to me the right level of testing because those are publicly documented, so they are a kind of API we are exposing to the world. Any test that relies on deeper details of implementation (such as values of the private `_LP_*` variables or the `_lp_*` functions) will be a pain to maintain.

**Comment by felixSchl** [comment]
@dolmen I think we are thinking very much alike. Unfortunately bats does not run on zsh, but we can easily enough run zsh from a test case. We still get plenty of benefits from using bats.

https://github.com/nojhan/liquidprompt/pull/470/files#diff-e83ee8c6737007c4e99566f73a1f8d65R12

I think we can spruce it up quite a bit still, but it should do for now. Once we have written say 3 or 4 tests a pattern will likely emerge that we can then abstract.

**Comment by nojhan** [comment]
See PR #470

**Comment by Rycieos** [comment]
I have written a test suite using [shunit2](https://github.com/kward/shunit2), and am running it with Github Actions. The test suite still does not cover much, but it is better then what we had before.

I hope to improve the test coverage before v2.0.0 final.
