### ISSUE TITLE
Official way to enable for all users

### ISSUE THREAD

**Issue by iainhallam** [nojhan/liquidprompt#473]
Shell: bash
Operating system: CentOS 7.2
Liquid Prompt version (tag, commit): downloaded from Git repo 2016-09-27

I've done the git clone operation in `/opt`, so I now have `/opt/liquidprompt/liquidprompt`. If I log in and do `source /opt/liquidprompt/liquidprompt` at the command line, it all works fine, but I created a one-line script with that content in `/etc/profile.d/prompt.sh`, and my terminal windows don't get the prompt by default. If I `su` to root, the prompt is working fine. My `.bashrc` is pretty vanilla for a CentOS 7 system:

```
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi

# Add user binaries
PATH=~/bin:$PATH
```

What's the best way to enable LP system-wide for all users, and could this be added to the documentation?

**Comment by dolmen** [comment]
Liquid Prompt must be loaded from `bashrc`, not from `profile` as written in [README](../../liquidprompt#test-drive-and-installation). So you should probably create or modify ``/etc/bashrc` (`/etc/bash.bashrc` on Debian) instead of `/etc/prodile.d`.

I recommend to NOT use Liquid Prompt as root, so adding documentation about installing Liquid Prompt system-wide is not a good idea.
