### ISSUE TITLE
Support 256 colours when the terminal can display them

### ISSUE THREAD

**Issue by iainhallam** [nojhan/liquidprompt#486]
Shell: bash
Operating system: CentOS 7
Liquid Prompt version (tag, commit): 1.11

I'm using the Solarized theme for a lot of my editors, and terminals (see http://ethanschoonover.com/solarized) so I'd like to be able to make a Solarized liquidprompt theme, but the only colours available are pretty stark. Is there a way that liquid prompt could detect whether the terminal supports 256 colours and allow higher-indexed colours to be specified in that case?

**Comment by dolmen** [comment]
Terminal emulation is a mess. Many terminal emulator do not set properly a proper `TERM` value (and instead just export `xterm`) and many operating systems (especially if you consider old versions) do not have proper terminfo definitions for all modern terminals.

And there is one thing nobody wants: a corrupted shell prompt because of incorrect terminal destection (because a broken shell prompt makes fixing the OS configuration even less easy, so most people will just drop the "advanced but broken" prompt).

Anyway enabling your theme if `tput colors` says 256 should be quite safe.

**Comment by Rycieos** [comment]
[v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1) has a new function supporting this: [`lp_terminal_format()`](https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/functions/public.html#lp_terminal_format). See the link for documentation.

The preset colors (`$BLACK`, `$RED`, etc.) do not support extended colors, as that would be a breaking change for users.
