### ISSUE TITLE
Disabling/enabling features

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#50]
As pointed out in pull request #42 and #49, the `LP_ENABLE_*` variables and `*.ps1` template files are doing more or less the same job.

At the moment, the advantages of having both systems are:
- it is simpler for newbies to edit an `LP_ENABLE` variable than to edit `LP_PS1`,
- it permits to keep complex existing template codes while disabling a specific feature (and thus we could have out-of-the-box templates like "laptop" or "server"),
- it is faster than parsing the `LP_PS1` variable for checking what's asked,

Drawback:
- if you do remove a feature from your  `LP_PS1`, you still have to disable it if you want to save speed.

Any idea on how to achieve an elegant features  enabling system?

**Comment by Rycieos** [comment]
I have decided: the `LP_ENABLE_*` config options are the right way to disable features, as they are the fastest, and the easiest for users to change.

Future themes like those in [v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1) should call all data functions, and those that return ``false`` (either because they have no data or because the user disabled them) will not be displayed to the user.
