### ISSUE TITLE
Git support vulnerable to arbitrary command execution

### ISSUE THREAD

**Issue by ericbn** [nojhan/liquidprompt#519]
Shell: Zsh (with Zim)
Operating system: MacOS
Liquid Prompt version (tag, commit): 9c80396

Git raw ref names are subject to expansion by the shell. Avoid putting raw ref names in the prompt to protect the user from arbitrary code execution via specially crafted ref names (e.g., a ref named `'$(IFS=_;cmd=sudo_rm_-rf_/;$cmd)'` would execute `'sudo rm -rf /'` when the prompt is drawn). 

How to reproduce (make sure showing Git information is enabled):

    $ git clone https://github.com/njhartwell/pw3nage
    $ cd pw3nage
    $ git checkout \$\(./pw3n\)

See:
- https://github.com/njhartwell/pw3nage
- git/git@8976500

**Comment by Rycieos** [comment]
It seems like the solution used by git (in the linked git issue) of putting the branch name in a variable would be the easiest and simplest way to fix this.

While this is a weird and edge case issue, it's worth fixing.

**Comment by ericbn** [comment]
Exactly. That's how we fixed it in Zim's git_info also: https://github.com/Eriner/zim/pull/159/files

**Comment by dolmen** [comment]
I'm have not been able to reproduce the issue under LiquidPrompt on Linux with either bash or zsh. That's why I published [a statement](https://github.com/njhartwell/pw3nage/issues/3) when the pw3nage repo appeared.

Note that a quick look at Zim tells me that it is full of other similar vulnerabilities as in many places in the git-info module variables are not properly quoted. But this is off-topic here.

**Comment by Rycieos** [comment]
I am also unable to reproduce this. This looks like another case of combining multiple custom prompts.

I would say the issue is in Zim, but they claim to have fixed the problem. This is probably caused by the combination of Zim and liquidprompt, which liquidprompt has never claimed to support such usage.

**Comment by ericbn** [comment]
Yeah, looks like this is some issue on how Zim integrates with liquidprompt. I was not able to reproduce it outside Zim either. So closing this.
