### ISSUE TITLE
CPU usage can't be computed from load

### ISSUE THREAD

**Issue by pichi** [nojhan/liquidprompt#530]
Shell: bash/zsh
Operating system: Linux
Liquid Prompt version (tag, commit): master 9c80396

/proc/loadavg contain load but liquidprompt show CPU percentage. There is not a way to transform load into the percentage. The load is traditionally defined in queue theory as an average number of processes waiting for execution. Imagine this hypothetical example. You have 100 processes scheduled at the start of each second and each process takes 10ms to execute and one CPU to run it. Then your load would be 50 but your CPU utilization would be 100%. Then you take one process running non-stop. Your CPU utilization would be 100% but your load would be 0 or 1 depending if you include running process into load calculation which Linux does. But I'm not sure. Anyway, the load could be way over 1 on single CPU system and CPU utilization could never be over 100%. Unfortunately, this is exactly what I see using liquidpromp, CPU over 100% shown in white. It is not right. Correct way how to compute CPU utilization is to read the first line of /proc/stat

Something like
```
$ read _ user nice system idle iowait irq softirq steal guest guest_nice eol < /proc/stat
$ old_cpu_sum=$(( user + nice + system + idle + iowait + irq + softirq + steal + guest + guest_nice ))
$ old_cpu_idle=$idle
# after some while, command, next prompt rendering, ...
$ read _ user nice system idle iowait irq softirq steal guest guest_nice eol < /proc/stat
$ new_cpu_sum=$(( user + nice + system + idle + iowait + irq + softirq + steal + guest + guest_nice ))
$ echo $(( 100 - (old_cpu_idle - idle) * 100 / (old_cpu_sum-new_cpu_sum) ))%
29%
```
And now this is right CPU usage value.

**Comment by Rycieos** [comment]
You are correct, load average is not the same as CPU usage. However, there is a reason that `/proc/stat` isn't used.

`/proc/stat` isn't a Unix standard. Cygwin doesn't support it, and SunOS and BSD don't either (to be fair, they don't support `/proc/loadavg` either, but at least you can get load average from the `uptime` or `sysctl ` commands, respectively).

Most things under `/proc` are Linux specific, and this project aims to support most Unix systems. Ideally we would find a solution that works on Unix in general.

I will note that right now we are getting the CPU usage differently on different systems: https://github.com/nojhan/liquidprompt/blob/9c80396021a8106bfaeade9a1ea51b85152e951d/liquidprompt#L186-L206
If we changed the Linux part to your solution, we would have to add a section detailing the old way for Cygwin, since Cygwin reports as Linux, which would add complexity.

**Comment by Rycieos** [comment]
This is the official tracking issue for this problem. I don't want to edit the original bug report, so this comment will become the authoritative tracker of progress here. As reported by the community, here are the issues with the current "load percent" system:

- [x] Any value over 100% doesn't display with color (Fixed on master; soon to be in v1.12)
- [ ] System load doesn't track what percentage of the time that the CPUs are working.
- [ ] System load doesn't have any upper bound; if a user scheduled infinite tasks, there would be infinite load.
- [ ] Setting any ceiling value will be too low for some, and too high for others.
- [ ] System load and CPU count aren't strictly related.

Getting a true CPU usage percentage would be great, but it's not easy. From my digging, you need `mpstat` from the `sysstat` package to get a good interface into this, but you need to then enable a daemon to have it monitoring in the background. Otherwise, `mpstat` needs to sleep for a bit after calling it so it can sample multiple times (obviously not acceptable to sleep during prompt gen). Non of this is impossible, but it's no where as simple as getting load average.

It's fine to use a `/proc/` interface on Linux, but we need a comparable solution for *BSD, OS X, and SunOS.

Here is what I am thinking:
- Keep the current load average code in, but get rid of the strange dividing by 100 that tries to make it seem like a percentage. Maybe let the user configure the "ceiling" where the color stops advancing. This would expose the "raw" load average to the user (maybe don't divide by the CPU count?), which should be more useful.
- If possible, add a new system that tracks CPU usage percentage. If this can happen, make it the default thing to display instead of the load percentage. But obviously the user could pick which they want to see.

I don't want to launch 2.0 without a fix here, but I'm a bit stuck on this one. I would appreciate any feedback, ideas, or PRs on this.

@pichi @toreanderson @alyssais thoughts?

**Comment by toreanderson** [comment]
Well, the load average is an established, cross-platform metric. When a system administrator tells you the system has, e.g., *«a 4.5 5-min load average»*, you know exactly what is being communicated.

Therefore I would suggest to KISS and represent the canonical load average for what it actually **is**, and not making any futile attempts to convert it to something which it is **not** (such as CPU utilisation). The commits in #604 does just this.

If you want to output CPU utilisation as well, using `mpstat` or whatever, fine  – but make that into a new and separate module. Don't try to consolidate two fundamentally incompatible metrics into one.

When it comes to colour scale ceiling, it would probably be ideal to make it configurable. However, you need to decide on a default value in any case. My claim is that the current (default) ceiling – 1.00 on a single-core machine, meaning the "worst" colour appears at 0.90 – is way too low for essentially *any* use case. 2.00, as #604 sets it to, seems like a better choice. 4.00 would probably be okay too, but perhaps a little too high.

I think that the colour scale ceiling and display threshold should be multiplied with the number of CPUs by default (but feel free to make it configurable). A load of, say, 4.00 on a single-core machine is quite high, while a 48-core machine would essentially be idle. Multiplying the ceiling/threshold with the number of CPUs is necessary to make the default behaviour useful - and you'll want to be able to share one `liquidpromptrc` between multiple machines with differing CPU counts. That said, the number that liquidprompt adds to the prompt should indeed be the canonical/"raw" load average instead of any internal per-CPU normalisation, because that is the number that actually makes sense to a regular user. You'll find that fixed in #604 too.

Another little quirk I thought I'd mention is that the threshold is tested with `>`: https://github.com/nojhan/liquidprompt/blob/953e577ecef68968938bcc2e98e081daffe18aec/liquidprompt#L1493

I would suggest changing that to `>=`, so that it is possible to set the threshold to 0 and if you want the load symbol to always appear. With the current `>` test , even if you set the threshold to 0, the symbol will not display until the load average reaches 0.48 on a 48-core system. It also makes the point where the load symbol first appear with not quite match with the points where the colours changes. With the ceiling doubled (cf. https://github.com/toreanderson/liquidprompt/commit/482ea69abcf329ad69417bf2cf5faa072b47ec9a), this is the actual table of when colours appear/change:


Colour      | 1 CPU | 2 CPUs | 4 CPUs
------------|-------|--------|-------
YELLOW      | 0.61  | 1.22   | 2.44
BOLD_YELLOW | 0.80  | 1.60   | 3.20
RED         | 1.00  | 2.00   | 4.00
BOLD_RED    | 1.20  | 2.40   | 4.80
WARN_RED    | 1.40  | 2.80   | 5.60
CRIT_RED    | 1.60  | 3.20   | 6.40
DANGER_RED  | 1.80  | 3.60   | 7.20

As you can see, the `YELLOW` range is a little bit shorter than the others, and does not start on a load average value divisible by 0.1. This is of course just a cosmetic issue, but it does seem a bit inconsistent.

**Comment by toreanderson** [comment]
I just pushed a new branch with the fixes I mentioned in my previous comment: https://github.com/nojhan/liquidprompt/compare/master...toreanderson:fix/issue_530

I maintain that applying these would take liquidprompt's current load feature from «nonsensical» to «useful», fix this issue, and provide a reasonable basis for further improvements (such as making the colour scale ceiling configurable).

**Comment by Rycieos** [comment]
I opened #650 with a potential fix for this issue. @toreanderson it pretty much does what you suggested, namely display the real load average, while keeping the functionality exactly the same.

Please test and let me know what you think!

**Comment by Rycieos** [comment]
This has been changed in [v2.0.0-rc.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-rc.1).

Now the actual load average is displayed, while keeping the threshold and color calculations the same. This means the functionality is no different, just that the display has changed formats.

To make the configuration option `LP_LOAD_THRESHOLD` less confusing, it too has been changed to be an actual load value, no longer "centiload". Old values are still supported, which is done by checking for a period ('.') in the string. So for this historical reason, all new values must have a period in them.

A new config option `LP_LOAD_CAP` was added, to configure the range for color values output by `_lp_color_map()` for load averages. It too takes a load average float value. As it does not have the historical reason above, it does not accept "centiload" values.
