### ISSUE TITLE
`who` doesn't exist

### ISSUE THREAD

**Issue by jean** [nojhan/liquidprompt#532]
Shell: bash/zsh
Operating system: Android (7.0), using https://github.com/Bash-it/bash-it under https://termux.com/ 
Liquid Prompt version (tag, commit): 9c803:master

When starting a new shell session:

```
No command 'who' found, did you mean:                                                                                                                            Command 'echo' from package 'coreutils'
 Command 'wc' from package 'coreutils'
 Command 'sh' from package 'dash'
 Command 'gio' from package 'glib-bin'                                                                                                                           Command 'go' from package 'golang'                                                                                                                              Command 'ht' from package 'ht'                                                                                                                                  Command 'whois' from package 'inetutils'
 Command 'php' from package 'php'
Command 'w' from package 'procps'
Command 'co' from package 'rcs'
Command 'w3m' from package 'w3m'
Command 'wol' from package 'wol'
```

```
24-14:18📈 121% [u0_a237:~] $ alias who=whoami
24-14:19📈 118% [u0_a237:~] $ reload                                                                                                                                                       
liquidprompt: terminal screen not supported                                                                                                                     
liquidprompt: terminal screen not supported                                                                                                                     
whoami: extra operand 'am'                                                                                                                                      
Try 'whoami --help' for more information.
```

(In the prevous code block I changed the fancy liquid prompt to `$` because somehow I was pasting lines without linebreaks, which was b0rking github issue display.)

**Comment by jean** [comment]
Ah, turns out that _Command 'w' from package 'procps'_ is the missing one.

**Comment by Rycieos** [comment]
The `who` command is only used to determine where you are logging in from. This is in turn only used to determine if the hostname needs to be displayed. See: https://github.com/nojhan/liquidprompt/blob/9c80396021a8106bfaeade9a1ea51b85152e951d/liquidprompt#L596

You can disable the hostname check (and therefore it's display) by setting `LP_HOSTNAME_ALWAYS` to `-1`.

It's worth noting that the `who` command is used to see users that are logged on, with their terminal, date, and hostname that they are connecting with. `who am i` only shows lines that match your own current user session. Liquidprompt uses this to determine if your current session is local or not. This is why the `whoami` command won't work as a replacement, as it doesn't have terminal information.

I don't think this is a Liquidprompt bug, since `who` is standard on Unix. You could install the `who` command either by installing Busybox or through Termux's package manager.
