### ISSUE TITLE
Causes slow response in bash shell

### ISSUE THREAD

**Issue by michK** [nojhan/liquidprompt#535]
Shell: bash
Operating system: Mac OS
Liquid Prompt version (9c80396):

Liquidpromp is causuing my bash shell, both in Terminal and iTerm2, to be slow to react to every command.

When I hit enter to enter a command, it consistently takes +- 2 seconds for the terminal to respond. Disabling Liquidpromp fixes this.

**Comment by Rycieos** [comment]
We need a lot more information to diagnose the issue.

Please include your Bash and OS version.

Try setting `LP_DEBUG_TIME=1` in your config to see actual timings for prompt generation. Try disabling specific features to see what features are taking the most time.

This sounds similar to the many reports of liquidprompt being very slow on Windows; those are caused by disk I/O being slow.

**Comment by ronkitay** [comment]
I'm experiencing the same issue - although not 2 seconds - but it is very noticeable.
When I enabled timing I got this for just pressing `enter`:

```
real	0m0.370s
user	0m0.162s
sys	0m0.269s
```

When pressing on `enter` when not in my git repo, it was way faster:

```
real	0m0.085s
user	0m0.034s
sys	0m0.047s
```

When I tested it on `liquidprompt` repo - it was faster than in my repo - but still two times slower than when not in a repo:

```
real	0m0.173s
user	0m0.063s
sys	0m0.084s
```

I'm running on a MacBook Pro with (16GB, 2.5 GHz) with El Capitan (10.11.6) and Bash version is:

```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Setting LP_ENABLE_GIT=0 solved the slowness naturally. 

I previously had a prompt that runs `git symbolic-ref HEAD 2> /dev/null | cut -d"/" -f 3-` and `git rev-parse --show-toplevel | sed 's/.*\///'` each time and it worked very fast - so I don't think the problem is in asking `git` if the current directory is under a vcs root .

I also disabled other source control features like SVN and Mercurial since I'm not using them - it had no effect on performance.

I hope this is helpful - please solve this problem, I'd like to use `liquidprompt` but with such noticeable lags I can't.

**Comment by spdaly** [comment]
Having the same issue.  No performance issues is non-git folders.  Once I'm in a git folder prompt slows way down.  Setting LP_ENABLE_GIT solves the problem.

git version 2.16.0
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)

I found this issue on another project that sounds like a similar problem: https://github.com/Bash-it/bash-it/issues/914

**Comment by michK** [comment]
My bash version is:
`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)`

And my os version is: macOS High Sierra 10.13.3

I recently updated to High Sierra, but had the same problem with the previous version.

When I set LP_DEBUG_TIME=1, and do `ls` in my home directory I get:

```
real	0m1.713s
user	0m2.005s
sys	0m0.102s

```
When I do `ls` in a git directory I get:

```
real	0m3.680s
user	0m4.141s
sys	0m0.138s
```

I'll play around and try disabling things to see what is causing this and report back

**Comment by mathomp4** [comment]
OS: SLES12 SP3
Bash: `GNU bash, version 4.3.42(1)-release (x86_64-suse-linux-gnu)`

Here's a fun data point. When I go into a repo that has ~15 submodules:

```
05:29:38 [mathomp4@pfe22:/nobackup/gmao_SIteam/Baselibs] $ cd ESMA-Baselibs-5.1.3/src/

real	0m20.734s
user	0m0.398s
sys	0m6.560s
05:30:04 [mathomp4@pfe22:/nobackup/gmao_SIteam/Baselibs/ESMA-Baselibs-5.1.3/src] 78ce54c(+0/-0) ± 
```

**Comment by michK** [comment]
In the meantime I have formatted my macbook and liquidprompt now works fine.
