### ISSUE TITLE
Use LC_ALL=C (high priority/override LANG) instead of LANG (low priority) for getting 'C' numbers 

### ISSUE THREAD

**Issue by mathiasp** [nojhan/liquidprompt#548]
Shell: bash/zsh
Operating system: FreeBSD 
Liquid Prompt version (tag, commit): 9c80396021a8106bfaeade9a1ea51b85152e951d

You seem to use LANG=C to get numbers in 'C' format, but this is the low priority fallback variable.
If LC_ALL is set, this overrides LANG. 

Citing e.g. from the GNU docs:

> "LC_ALL is an environment variable that overrides all of these. It is typically used in scripts that run  particular programs. For example, configure scripts generated by GNU autoconf use LC_ALL to make sure that the configuration tests don’t operate in locale dependent ways. " 
https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html

For me your current use means I get german numbers back from _lp_cpu_load, which in turn gives me an error at every prompt.

**Comment by Rycieos** [comment]
Are you setting `LC_ALL` in your prompt? By your link, it really shouldn't be set by a user, since it overrides everything else. A user should be setting `LANG` somewhere in `.profile` or similar.

**Comment by mathiasp** [comment]
Yes, I know. I had to set it for some buggy program, a long time ago, and somehow kept it that way. Fixed it because of this bug.

That doesn't change the fact that programs that want to safely read numbers need to set LC_ALL instead of LANG.

**Comment by Rycieos** [comment]
We can't _set_ `LC_ALL` since `liquidprompt` doesn't just run once, it is loaded in the shell and runs before and after every command.

We could replace every command variable assignment to `LANG` with `LC_ALL`, which would prevent issues where a user set one of the `LC_XXX` vars or incorrectly set the `LC_ALL` var.

There are 5 uses of `LANG` as command variable assignments, 4 uses of `LC_ALL`, including one command where both are set (which seems to be pointless) in `liquidprompt`.

Reading the docs, it seems to be pretty straightforward that this is a logical change to make. I'll open a pull request and see what others think.
