### ISSUE TITLE
Desktop notification when long process ends

### ISSUE THREAD

**Issue by Rodsevich** [nojhan/liquidprompt#590]
Shell: bash
Operating system: Kubuntu

I'm just wondering if a feature to desktop notify when a process that exeeded some threshold ends exists or is in plans of being added or sth. I'm inspired on this: https://askubuntu.com/questions/409611/desktop-notification-when-long-running-commands-complete

**Comment by Rycieos** [comment]
A related feature was just merged: #571.

A prompt program can only do so much, and interacting with the terminal is about as far as it can go. That isn't to say that we couldn't run some sort of command in that case, but I think that the bell ringing is a good way to do that.

In my terminal (Mintty), I can enable a feature to send a notification when the bell is rung.

Despite the "wontfix" label, I would probably accept a PR for this if it was done well, but I don't think there is a need for it now. I'd be happy to be convinced otherwise.
