### ISSUE TITLE
Changing color for LP_PS1_PREFIX

### ISSUE THREAD

**Issue by Rmano** [nojhan/liquidprompt#593]
Shell: zsh
Operating system: Ubuntu 18.04
Liquid Prompt version (tag, commit):  5f4aeece8

Hi, I tried to change the color of the prefix for the prompt with 

     LP_PS1_PREFIX="${RED}TL19${BLACK}" 

and with 

     LP_PS1_PREFIX="\${RED}TL19\${BLACK}"

...but neither worked. I suppose it's probably an user (me) problem; how should I fix this?

**Comment by Rodsevich** [comment]
Neither to me. I'm seeing that the colors are local variables, so nothing is defined when used maybe. That should be a bug

**Comment by Rycieos** [comment]
It's not a bug, it's designed behavior. See:
https://github.com/nojhan/liquidprompt/blob/5f4aeece8d6cf98138e729f7833e11e985ca44d3/liquidprompt#L255-L258

If you would set this in your config, then it would work correctly, since those locals are still loaded when your config file is loaded. But my guess is that you want to be able to do this on the fly. If that's the case, try doing this in your config:

```sh
MY_RED="${RED}"
```

And then when you want to set the prefix later, you can call `prompt_tag()` instead of setting the prefix manually, and `NO_COL` instead of guessing what to reset to:

```sh
prompt_tag "${MY_RED}TL19${NO_COL}"
```

**Comment by Rodsevich** [comment]
But why? There should be a configurable way of setting the color but changing that lib's file, doesn't it?

**Comment by Rycieos** [comment]
I'm not sure what you mean. If you are fine with setting it not during runtime, you can do it in the config file.

**Comment by Rodsevich** [comment]
As a normal user I have a .config/liquidpromptrc file that defines a `LP_PS1_FILE=~/.config/liquidprompt/my_own.ps1` which points to a file that sets the LP_PS1. in that last file I can't use ${BLUE} in that LP_PS1 variable to set the color to blue, I gotta do those weirdos of \e[033m if I want any color. But that breaks the history loggings of the CLI. So I end up with a colorless boring PS1.
You suggest that I define `MY_BLUE="${BLUE}"`... in where? I understood it should be in the liquidprompt main file, which is in /usr/lib or sth over there. While the good practise one should be in $HOME, shouldn't it?

**Comment by Rycieos** [comment]
You should do it in `~/.config/liquidpromptrc`. The RC file is loaded only once, during the initial setup, so it will have access to the `${BLUE}` var. Then you can use it in your `my_own.ps1` file like you wanted.

**Comment by Rodsevich** [comment]
Now it worked!
 + What's the reason to no have the colores prefixed with LP_ and avoid this non-intuitive behavior here?
 + Would a PR with `LP_BLUE="${BLUE}"`, `LP_RED="${RED}"`, etc in the `liquidpromptrc` default file be accepted?

**Comment by Rycieos** [comment]
I don't have authority to merge PRs.

That said, I doubt such a PR would be accepted. It's setup that way so that it can be referenced in the config file if needed, since almost all use cases would use it there. In the rare case someone wants to use it later (like what you are doing in a `.ps1` file), they can make it themselves, or even better, construct their own string in the config file like so:
```bash
LP_CUSTOM_PS1_PREFIX="${RED}TL19${NO_COL}"
```
and then reference that whole var when they want it:
```bash
prompt_tag "${LP_CUSTOM_PS1_PREFIX}"
```

**Comment by Rycieos** [comment]
> I don't have authority to merge PRs.

I just remembered that saying that inspired me to email @dolmen. What did I get myself into 😄 

Starting with [v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1), [`lp_terminal_format()`](https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/functions/public.html#lp_terminal_format) can be used to generate colors, in 256 color if your terminal supports it. This is preferred over the temporary color variables that are only loaded while the config file is being sourced.

For example, if you want your color to be saved and ready anytime, add this to your shell RC file:
```bash
lp_terminal_format 1
RED=$lp_terminal_format
```

Feel free to ask questions.
