### ISSUE TITLE
Idea : prompt with updating time to remember when a command was launched

### ISSUE THREAD

**Issue by Siltaar** [nojhan/liquidprompt#601]
Shell: bash/zsh
Operating system: GNU+Linux Debian
Liquid Prompt version (tag, commit): ---

I read this blog-post and thought that liquidprompt team might be interested in implementing such a feature :
- https://redandblack.io/blog/2020/bash-prompt-with-updating-time/

In short, instead of showing the timestamp of the prompt creation, the feature is to show an empty timestamp until the next command is launched, and at this time, the current prompt timestamp is updated.

So when a command takes 20 minutes to run, you're not confused by the fact that your two previous prompts (current empty after the command, and the one which launched the command) are showing a 1h interval, because you took 40min to type the command.

This is the future, liquidprompt is the future :-)

**Comment by Rycieos** [comment]
Cool feature, something I would want for sure.

Looks pretty involved though, it will probably require a lot of rework, so it will have to wait for 2.0.

**Comment by Rycieos** [comment]
I dug deep to figure out if this could be done:
1. Crossplatform: all supported OSs
2. Cross-shell: both Bash and Zsh
3. Backwards compatable: supported back to Bash 3.2.

These are our current support requirements, and if a feature can't do that, we can't use it.

The short answer is "probably not".

Long answer:
The linked blog post uses the `PS0` Bash variable to print something after the user hits return on a command. This was added in Bash 4.4. This fails 2 and 3 above.

But since we are already running code after a user hits return (for saving the time for timing long running commands), we should be able to print something to the screen on all shells, just not using `PS0`.

The larger issue is moving the cursor. As far as I can tell, all our supported environments support saving and restoring the cursor (`tput sc` & `tput rc`), but the problem is that we need to save two locations: the end of the prompt, and the start of the printed time. This is not simple.

Some terminals support "registers" for multiple screen location saving, but most don't.

Most terminals support a way to query the terminal for the current cursor location, but this too has issues:
1. I said most terminals: not all do.
1. One way from [this answer](https://unix.stackexchange.com/a/88304/421569) is to redirect the terminal elsewhere while we read from it. This is hacky, ugly, and not portable.
1. Another way also from [this](https://unix.stackexchange.com/a/88304/421569) and [this answer](https://unix.stackexchange.com/a/183121/421569) is to print the code and read all in one command: `IFS= read -sd R -p $'\E[6n' curpos`.

This last one seems to work, but it's not universally supported. It's labeled as a "extension for ANSI ENQ".
https://www.xfree86.org/current/ctlseqs.html
https://invisible-island.net/xterm/terminfo-contents.html

While it works great on my terminal, I can't find any documentation on it for BSD, and the only ID I have found for it is `u7`, which is a terminfo spec, not a termcap (so again, won't work on BSD).

The larger issue is how do we save a location partway through a prompt? Yes, in Liquidprompt and the blog post, the time is at the start of the line, but it doesn't have to be. We could put it anywhere. There is no way to know where the time starts, as we don't print the text to the screen, we put it in `PS1` where the shell prints it. I see two fixes:
1. Force the thing we want to overwrite be at the start of the screen. Ugly.
2. Re-print the _entire_ prompt. This might fix a few other issues, like VCS display being out of sync, not just time.

The second option can be slow though; ideally when you hit return on a command, it starts running right away, not after the display updates.

The problem is that we can't. For the same reason we can't `echo` parts of the prompt to the title or the screen: we are relying on the shell to interpret codes like `\w` for us, which only happens in `PS*` expansion. This includes the current time. The reason it worked in the blog post is they were using `PS0` to expand it, which we can't use.

So the only way we can make this work is either:
1. Use features that won't work for all users
2. Only overwrite the very first part of the prompt, and it has to be literal strings, no shell escapes.

And the character saving isn't supported by all terminals anyway.

So my official decision is that this is too difficult to make work on all supported platforms.

As always, I'm open to new info and/or working examples.

**Comment by Siltaar** [comment]
Thanks nevertheless for the digging up.
