### ISSUE TITLE
Toolbox containers support?

### ISSUE THREAD

**Issue by t-chaik** [nojhan/liquidprompt#612]
### Description

[Toolbox](https://github.com/containers/toolbox) is a utility targeting developers that let you run mutable containers closely integrated with your regular working environment (typically full home access). That means you get the benefits from liquidprompt inside your dev. container for free.

However, there's currently nothing in the prompt indicating that your running in the container. Toolbox [normally prepends a box symbol to that prompt](https://github.com/containers/toolbox#enter-the-toolbox) but liquidprompt overrides it. Would be nice for liquidprompt to detect such environments and display something like that box symbol itself.

### How will this be useful?

That would help quickly identifying shells running in a container.

**Comment by Rycieos** [comment]
Seems closely related to #569. I'll ask the same question I did there: how do you inject Liquidprompt into the container?

Sounds like an obvious good feature, I'll add it to the roadmap.

**Comment by t-chaik** [comment]
> How do you inject Liquidprompt into the container?

Well, if you already source the liquidprompt script from your host's `.bashrc` then you get it automatically: your home in the container is your regular home from the host (assuming liquidprompt is sourced from your home directory / from a location that is available from the container)

**Comment by Rycieos** [comment]
It looks like `toolbox` looks for two files existing to determine if a shell is in a toolbox:
https://github.com/containers/toolbox/blob/e935ed893d5b72ac9f08987bc2c7ede9f7d506cc/profile.d/toolbox.sh#L38-L40

We should be able to duplicate that check, and copy their mark (`⬢`) and color (`\033[35m` translates to magenta foreground, or `lp_terminal_format 5`).

I'm not sure I can get `toolbox` working on any of my machines, since they are all running Docker, not Podman. Assuming that is the case, @t-chaik would you be able to test a patch when I create one?

**Comment by t-chaik** [comment]
@Rycieos: Sure !

**Comment by Rycieos** [comment]
@t-chaik I added commit ffc71cfafee0eac2ad7378a0aa582bd63c9e1a37 on branch [feature/container-status](https://github.com/nojhan/liquidprompt/tree/feature/container-status), if you can test that. I see no way that it couldn't work though.

**Comment by t-chaik** [comment]
Seems to be working fine indeed:
![image](https://user-images.githubusercontent.com/8634377/165596320-aae575d8-923a-47ef-91ea-7b2ae2063e36.png)
