### ISSUE TITLE
Runtime fails if the slow command is not the first one in a pipeline

### ISSUE THREAD

**Issue by nolanl** [nojhan/liquidprompt#614]
Shell: bash 5.0.3(1)-release
Operating system: Linux 4.19.0-9-amd64 (2020-06-07), Debian GNU/Linux 10 (buster)
Liquidprompt version: 869d4abb09cbd515b1aea4862c0c2e4c1791db91

### Steps to Reproduce
1. Set `LP_ENABLE_RUNTIME=1` and `LP_RUNTIME_THRESHOLD=5`
2. `sleep 2 | sleep 6`

### Expected Behavior
The prompt should report "6s".

### Current Behavior
The prompt reports no time.

**Comment by Rycieos** [comment]
I can confirm this, bash 4.4.19(1)-release.

Zsh doesn't seem to have this problem.

This is a really interesting one, nice find. I'll have to do some digging, but this might end up being a bash bug, in which case I'm not sure we can fix it.

**Comment by Rycieos** [comment]
Fixed on master and in [v1.12-rc.1](https://github.com/nojhan/liquidprompt/releases/tag/v1.12-rc.1). This would not have been easy to fix if I hadn't learned quite a bit working on #451.

**Comment by Rycieos** [comment]
Ok, this wasn't a complete fix. Turns out that if you hit enter on an empty prompt, Bash runs `$PROMPT_COMMAND`, but since it doesn't run any command, it doesn't run a DEBUG trap for the non-existant command. Duh. This means if you press enter twice on an empty prompt, it will show timing on the second one (if enough time passed). Fixed in 25cd5dcba4832c2f0a374e954e56ec63c105d94e
