### ISSUE TITLE
$LP_ERR not set when loading configuration globally

### ISSUE THREAD

**Issue by sjaks** [nojhan/liquidprompt#631]
I am attempting to use liquidprompt version `1.11-3ubuntu1` globally on a server running Ubuntu 20.04.

When loading liquidprompt in one of the following files, the return code isn't displayed in the prompt because `$LP_ERR` won't get set:
```
/etc/profile.d/someloaderscript.sh
/etc/bash.bashrc
/etc/profile
```

When loading liquidprompt manually with `sjaks$ source /usr/share/liquidprompt/liquidprompt` after logon, the return code module works as expected.

My liquidpromptrc is stored in `/etc/liquidpromptrc` and liquidprompt itself is located in `/usr/share/liquidprompt/liquidprompt` (Ubuntu default).

**Comment by Rycieos** [comment]
> When loading liquidprompt manually after logon, the return code module works as expected.

This makes me sure it's a ordering error. Liquidprompt _must_ be loaded last, after all other programs that modify `$PROMPT_COMMAND`, or error code and timing won't work.

I have an [FAQ entry](https://github.com/nojhan/liquidprompt/wiki/FAQ#prompt-timing-isnt-working) for this. I need a new one that more closely matches this LP_ERR issue, since it seems unrelated, and users assume it's not their issue.

**Comment by sjaks** [comment]
Can confirm that user's .bashrc uses `PROMPT_COMMAND`. Return codes are properly printed if the lines setting `PROMPT_COMMAND` are removed.

**Comment by Rycieos** [comment]
Again, you shouldn't have to remove the lines, just have them before sourcing Liquidprompt.
