### ISSUE TITLE
Getting error: -sh: : command not found from master branch

### ISSUE THREAD

**Issue by ashleykleynhans** [nojhan/liquidprompt#643]
Shell: bash 4.2.46(2)-release

Operating system: Linux 3.10.0-1160.6.1.el7.x86_64, CentOS Linux release 7.9.2009 (Core)

Liquidprompt version: master

### Steps to Reproduce

1. Clone liquidprompt repo
2. Source it in /etc/profile.d/bash_custom.sh
3. Log in to the system 

### Expected Behavior

No "command not found" errors every time after executing a command in the shell

### Current Behavior

"command not found" errors every single time a command is executed in the shell

### Possible Solution

N/A

**Comment by Rycieos** [comment]
Can you please add the exact commit hash, instead of just master? I can not know if you actually have the current latest master, and master is always changing, so soon this issue will be out of date.

You say there are multiple errors printed each time. Can you add the exact text printed?

It seems to me like this is a problem with how you are loading Liquidprompt. Can you please add the section of your `/etc/profile.d/bash_custom.sh` that is loading Liquidprompt?

I know similar errors can be printed if you hook Liquidprompt without activating it first, ie:
```
$ . ./liquidprompt --no-activate
$ prompt_on
bash: : command not found
bash: __lp_path: command not found
bash: : command not found
bash: : command not found
```

**Comment by Rycieos** [comment]
Closing as there has been no update from the reporter.
