### ISSUE TITLE
Question: Why does 'master' get tags for WIP versions?

### ISSUE THREAD

**Issue by atifraza** [nojhan/liquidprompt#646]
I used to clone the repository instead of relying on distribution packages, because this provided the most up-to-date stable version of liquidprompt.

Recently, I was setting up a new system with the same script, and instead of a stable release, I ended up with a beta release when cloning the *master* branch.

My question is, why not develop and test the new versions on a *dev* branch?
I hope I did not miss something in the previous discussions regarding this aspect of development work.

**Comment by Rycieos** [comment]
This is a valid question and discussion point.

For a brief history: I took over as the lead maintainer of the project in May of 2020. Before May of 2016, this project did have a `develop` branch that was used as expected. You can see the removal of this standard in this commit: 9184ce7ab5598b68c1e793bfb44f2583bf9c3ea0. On removal, there was no clear answer as to if `master` is "stable" as well as being the development branch.

My understanding of general Git branching standards is this: `master` (or the new standard of `main`) is simply the default branch, and carries no further meaning like "stable", "development", or "latest". If you see a project with a branch named `master` or `main`, I think one should not make assumptions on what purpose that branch has.

That said, obviously Git has a concept of a default branch (aka repo HEAD). This is the branch that gets checked out by default when cloning.

Slightly related, I was planning on using the future Github tool to rename `master` to `main` when they launch the tool to make that painless.

Lastly, Liquidprompt has a "no breaking changes" policy, meaning anything merged should not break any existing use cases. So as for the for the [134 commits](https://github.com/nojhan/liquidprompt/compare/v1.12.1...master) on `master` since `v1.12.1`, non of those commits have *planned* breakage. That said, yes, I have marked "beta" tags on those commits. I expect there to be small bugs as development goes.

All that to say: yes, I agree. This project should (probably) have both a "stable" branch and a "development" branch. There are two related questions along with that:
1. Which should be default? (the branch that is checked out when cloning the project.)
2. Which should have the name `master` (or `main` in the future)?

The first question is not simple. Most users have come to expect that the default branch is tracking development. Also, if we change the default branch, that does not change the currently checked out branch for any user that has already cloned the repo. But I agree that tracking development is probably not the best idea.

The second question is easier. Probably the default branch should keep the default name.

This is a user focused topic, so I want to hear feedback on this.

**Comment by atifraza** [comment]
Thanks for the prompt response.

I have usually seen (and tried to adopt) a [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) workflow, which prompted me to ask the question.

In my view, the default branch should definitely be the one which has a release tag, which is usually the *master*/*main* branch.
The person cloning the repository for development is usually aware that the development branch has to be cloned separately.

However, if the *master* branch contains backwards-compatible changes, then I guess it is OK to keep development on the *master* branch (for the time being).
Once version 2.0 is finalized, may be a branch reorganization can take place after wards.

**Comment by Rycieos** [comment]
> The person cloning the repository for development is usually aware that the development branch has to be cloned separately.

Ah, that reminds me. The issue this project had before was that *many* potential contributors would clone the project and open PRs to the `master` branch instead of `develop`, since Github defaults to the default branch when opening a PR. And sometimes they would also base their work off of `master` as well, sometimes duplicating work that was already done on `develop`. That was despite clear instructions in the `CONTRIBUTING` file.

By setting the default branch to our development branch (`master`), we eliminated that problem completely. (Note that there is currently no way to separately set default branches for PRs and for cloning.)

In light of that, I am leaning towards adding a `stable` branch that tracks the latest stable release tag, along with clear instructions on the options in the install documentation. It's the simplest option (least change from current), and prevents the above issue.

I am still looking for feedback from users. This does not affect us maintainers much.

**Comment by atifraza** [comment]
The inclusion of such a branch named *stable* or *release*, and mentioning something on the lines that "non-developmental users should clone this specific branch" should do the trick.

**Comment by augmentedfourth** [comment]
The proposed addition of a `stable` branch that basically fast-forwards `master` each time there's a release also results in zero changes to the way this is distributed in Homebrew, so I don't have any concerns.

**Comment by Rycieos** [comment]
I added a new [`stable` branch](https://github.com/nojhan/liquidprompt/tree/stable), which currently points to `v1.12.1`, and will be updated to `v2.0.0` when that drops.

Commit c140a824d7bae729d9c92881f7821e8f2eb16974 pushed that adds documentation suggesting the new `stable` branch by default.
