### ISSUE TITLE
v2.0.0-beta.2 version string issue

### ISSUE THREAD

**Issue by aborrero** [nojhan/liquidprompt#652]
Version `2.0.0-beta.2` is problematic when packaging liquidprompt in Debian for a number of reasons.

Specifically:
* using the `-` character in the version string clashes with the use Debian packages makes of it. We use it to separate upstream version vs debian package version.
* for this kind of pre-release releases (beta, alpha, etc) the `~` character should be used instead, which sorts before the actual final version (i.e, `2.0.0~beta1` is detected to go before `2.0.0`).

How to address this:
* release a new version `2.0.0~beta3` or whatever
* drop the other 2 releases that contains the `-` character in the string.

Otherwise I will have a hard time packaging this for debian.

thanks!

More information: https://www.man7.org/linux/man-pages/man7/deb-version.7.html

**Comment by Rycieos** [comment]
I am having trouble understanding what the problem is.

1. Are you packaging pre-releases? I would expect a Debian package for v2.0.0, but not beta. Maybe release candidates? v2.0.0-rc.1 is soon.
2. Why does the version string this project picks matter? Why can't _you_ replace `-` with `~`? You already need to remove the leading `v` to follow those rules.
3. Are you talking about Git tags, or something else? Release Git tags should be immutable, so I shouldn't rewrite them. There were also v1.12-beta.1 and v1.12-rc.1 tags, were those not a problem?

I'm happy to accommodate packaging needs, I just need to understand the problem first.

**Comment by aborrero** [comment]
You are right, I will wait for 2.0.0 to be releases before packaging it.
