### ISSUE TITLE
Unable to set background color to white?

### ISSUE THREAD

**Issue by LudovicRousseau** [nojhan/liquidprompt#657]
I use a black on white terminal.
It looks like liquidprompt preverence is for white on black terminal. I could not find a theme using a white background.

Shell: bash 3.2.57(1)-release

Operating system: macOS Mojave 10.14.6, Darwin imac.xxx.fr 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64

Liquidprompt version: v2.0.0

### Steps to Reproduce
1. use the default color of the macOS Terminal
2. go into subdirectories

### Expected Behavior
I expect a nice prompt

### Current Behavior
The part corresponding to `LP_COLOR_PATH` has a black background.
I can change the foreground colour by setting LP_COLOR_PATH to $RED or something else.
But I could not find where to configure the **background** colour.
I was expecting to find something about this problem in https://liquidprompt.readthedocs.io/en/stable/config.html#colors but could not find anything related.

With the default configuration it looks like this:
![liquidprompt](https://user-images.githubusercontent.com/398496/107122175-5aa3cf00-6896-11eb-8720-af7b6a839560.png)

### Possible Solution
No idea.

I also could not find how to set the colour of the current directory 'liquidprompt' in the example above.
If I finally succeed in using a white background colour I will need to change the white foreground colour to black.

**Comment by Rycieos** [comment]
It looks like you have correctly configured your terminal to invert the basic 0-7 colors. The issue is that the colors used for the path are (by default) using the 8 bit color range (if supported). Your terminal either is not set to or does not support inverting those extended colors.

You can configure those color options to be more alike the rest of your terminal easily. See these parts of the documentation:

* [Config: Colors](https://liquidprompt.readthedocs.io/en/v2.0.0/config.html#colors)
* [`lp_terminal_format()`](https://liquidprompt.readthedocs.io/en/v2.0.0/functions/public.html#lp_terminal_format)
* [`LP_COLOR_PATH`](https://liquidprompt.readthedocs.io/en/v2.0.0/config.html#LP_COLOR_PATH)
* [`LP_COLOR_PATH_LAST_DIR`](https://liquidprompt.readthedocs.io/en/v2.0.0/config.html#LP_COLOR_PATH_LAST_DIR)
* [`LP_COLOR_PATH_SEPARATOR`](https://liquidprompt.readthedocs.io/en/v2.0.0/config.html#LP_COLOR_PATH_SEPARATOR)
* [`LP_COLOR_PATH_SHORTENED`](https://liquidprompt.readthedocs.io/en/v2.0.0/config.html#LP_COLOR_PATH_SHORTENED)
* [`LP_COLOR_PATH_VCS_ROOT`](https://liquidprompt.readthedocs.io/en/v2.0.0/config.html#LP_COLOR_PATH_VCS_ROOT)

Note that the last part of your path, the 'liquidprompt', is colored with `LP_COLOR_PATH_VCS_ROOT` because you are in its VCS directory. You can disable that feature with [`LP_PATH_VCS_ROOT`](https://liquidprompt.readthedocs.io/en/v2.0.0/config.html#LP_PATH_VCS_ROOT), but then it would be colored with [`LP_COLOR_PATH_LAST_DIR`](https://liquidprompt.readthedocs.io/en/v2.0.0/config.html#LP_COLOR_PATH_LAST_DIR) instead.

If any of that documentation has issues or you are still confused, let me know how it can be improved, and I'll reopen this issue and fix the docs.

**Comment by LudovicRousseau** [comment]
Thanks for the answer.
Yes, I can change the **foreground** colour to RED using `LP_COLOR_PATH_LAST_DIR=$RED`.
But my problem is that I want the **background** colour to be white instead of black.

I have not configured my terminal to invert the colours. I use the default configuration for the Terminal macOS application. The profile is called "Default".
![Preferences](https://user-images.githubusercontent.com/398496/107124938-f3424b00-68a6-11eb-9c76-52706d762b61.png)

In the screenshot I attached in my first message you can see that only part of the prompt has a black background. Where does the black background comes from? How to change it?

**Comment by Rycieos** [comment]
The black background comes from the 5 color configuration options I listed above. Specifically the second number in each tuple.

If you aren't changing the default color options at all, then your terminal emulator must be inverting colors.

I don't know anything about themes in the default MacOS terminal emulator, so I don't know if it is possible to invert the 8 bit color range.

Doing something like
```bash
lp_terminal_format 235 255 0 0 0 7
LP_COLOR_PATH=$lp_terminal_format
```
Would probably invert that specific color portion.

Though the `$RED` and similar colors do not set the background color, only the foreground color. If your terminal emulator doesn't invert the background colors, then maybe
```bash
lp_terminal_format 235 -1 0 0 0
LP_COLOR_PATH=$lp_terminal_format
```
would work instead.

**Comment by LudovicRousseau** [comment]
I have a white background if I use `lp_terminal_format 235 -1` or just `lp_terminal_format 235`.
My problem with the black background comes from the use of 0 for the background colour in https://github.com/nojhan/liquidprompt/blob/master/liquidprompt#L250

According to https://en.wikipedia.org/wiki/ANSI_escape_code#Colors the code 0 is for black. No need to "invert the colours".
The use of `lp_terminal_format 255 0 0 0 7` to define `LP_COLOR_PATH` specifically asks for a white (255) text on black (0) background.

Maybe liquidprompt could have a theme for terminals using black text on white foreground?

I am also very surprised by the use of `lp_terminal_format`.  The function does not return anything but set a variable with the same name as the function as a side effect? Very strange. In fact I did not understood how to use this function until you gave me an example above.
I would be less surprised by something like: `LP_COLOR_PATH=$(lp_terminal_format 235 -1 0 0 0)`.

Maybe you could add an documented example in the documentation for `lp_terminal_format` https://liquidprompt.readthedocs.io/en/v2.0.0/functions/public.html#lp_terminal_format

I found a solution to my problem. You can close the issue, or keep it open if you plan to implement the suggestions I propose.

**Comment by Rycieos** [comment]
> I have a white background if I use `lp_terminal_format 235 -1` or just `lp_terminal_format 235`.
> My problem with the black background comes from the use of 0 for the background colour in https://github.com/nojhan/liquidprompt/blob/master/liquidprompt#L250
> 
> According to https://en.wikipedia.org/wiki/ANSI_escape_code#Colors the code 0 is for black. No need to "invert the colours".
> The use of `lp_terminal_format 255 0 0 0 7` to define `LP_COLOR_PATH` specifically asks for a white (255) text on black (0) background.

Correct. And most of the prompt defaults to white text, but your terminal is changing it to black text. I guess your terminal is only changing the default colors, and none of the specific colors.

> Maybe liquidprompt could have a theme for terminals using black text on white foreground?

This was requested in #592. See my final https://github.com/nojhan/liquidprompt/issues/592#issuecomment-742763452.
In a "normal" terminal like mine, there is no way to make the shell print a background color across the whole line, which is why you still see large black sections in my screenshot. I don't know how to fix that, but I'm willing to try something if anyone has some helpful information.

My end conclusion was that it was not possible to make an inverted theme without making changes to the terminal emulators color output.

Your case is different though, where your terminal has changed the default colors and nothing else. This works for most of Liquidprompt, as most of the default colors are the default text, and all have the default background.

The issue is in the path. This section uses 256 colors to make slightly different shades of white to indicate differences in path sections. While these default formats could not set the background, that would look even worse in your case, as it would render white on white.

> I am also very surprised by the use of `lp_terminal_format`.  The function does not return anything but set a variable with the same name as the function as a side effect? Very strange. In fact I did not understood how to use this function until you gave me an example above.
> I would be less surprised by something like: `LP_COLOR_PATH=$(lp_terminal_format 235 -1 0 0 0)`.

The `var=$( ... )` syntax is a huge no-no, see #607. Removing all command substitutions for functions has made v2.0 _much_ faster than v1.12. I understand and agree that the usage is less clear, but the faster startup and prompt time is worth it.

> Maybe you could add an documented example in the documentation for `lp_terminal_format` https://liquidprompt.readthedocs.io/en/v2.0.0/functions/public.html#lp_terminal_format

I can add an example to all of the functions in the Public section.

> I found a solution to my problem. You can close the issue, or keep it open if you plan to implement the suggestions I propose.

I'm open to the idea of an "inverted" theme, if it works. But as I showed before, I don't think it can work without changing how colors are set in the terminal emulator. And if you need to change some colors in the terminal emulator, why not change more of them?

**Comment by LudovicRousseau** [comment]
One solution would be to:
- do not set the background colour i.e. let the terminal use the colour it wants
- do not use white or black colour for foreground so the text can be seen on a white and also a black background

You can use different levels of grey and check the text is readable using a white and a black background.
For example red and green are OK because this foreground colour can be used with either a white or black background.

I agree it will not be easy to do.

Note: on macOS the light theme (globally used by macOS) use black on white text in the Terminal application and the dark theme uses white on dark (but not really black) text in Terminal.
It if it not possible to have the same liquidprompt theme that can be used in light and dark macOS theme, it would be fine to have a theme that looks nice in the light theme. I think that would fix this issue and also https://github.com/nojhan/liquidprompt/issues/592

Here is what the default theme looks like in the dark macOS theme.
![dark](https://user-images.githubusercontent.com/398496/107152211-e1c07800-6966-11eb-86d8-38c8154d396f.png)
For the light macOS theme have a look at https://github.com/nojhan/liquidprompt/issues/656#issuecomment-774510218
![theme](https://user-images.githubusercontent.com/398496/107125049-b9be0f80-68a7-11eb-81fa-aecb81f4bc47.png)

The same liquidprompt theme can be used in both cases, except for the black background text that is ugly in light theme, and a bit strange in dark theme.

**Comment by Rycieos** [comment]
> 
> 
> One solution would be to:
> * do not set the background colour i.e. let the terminal use the colour it wants
> * do not use white or black colour for foreground so the text can be seen on a white and also a black background

The first part would be simple.

The second part would also be simple, but might ruin any possibility of a more nuanced default theme. This is what the default theme looks like (on a black background):
![image](https://user-images.githubusercontent.com/8375571/107152544-824a7400-6936-11eb-8b6e-b0e39a4b3c27.png)

The 5 different path colors make for some helpful information:
* The last path is highlighted.
* The VCS root directory is highlighted.
* Any directories shortened are lowlighted.
* Path separators are lowlighted.

To do what you said

> do not use white or black colour for foreground

We could try this:
```
lp_terminal_format -1 -1 0 0  # Nothing
LP_COLOR_PATH=$lp_terminal_format
lp_terminal_format 243 -1 0 0 7  # Grey
LP_COLOR_PATH_SEPARATOR=$lp_terminal_format
LP_COLOR_PATH_SHORTENED=$lp_terminal_format
lp_terminal_format -1 -1 1 0  # Bold, no color
LP_COLOR_PATH_LAST_DIR=$lp_terminal_format
LP_COLOR_PATH_VCS_ROOT=$lp_terminal_format
```
or, to use the older preformatted colors:
```
LP_COLOR_PATH=$NO_COL
lp_terminal_format 243 -1 0 0 7  # Grey
LP_COLOR_PATH_SEPARATOR=$lp_terminal_format
LP_COLOR_PATH_SHORTENED=$lp_terminal_format
LP_COLOR_PATH_LAST_DIR="${NO_COL}${BOLD}"
LP_COLOR_PATH_VCS_ROOT="${NO_COL}${BOLD}"
```
But I would prefer the former, more obvious.

This should work for both light and dark backgrounds. Could you give that a try?

I could be convinced to set that as the default.

**Comment by Rycieos** [comment]
Upon slightly further thought, I would rather use the "extended" range, and use `8` for grey, with a fallback to default color:
```
LP_COLOR_PATH=$NO_COL
lp_terminal_format 8 -1 0 0 -1
LP_COLOR_PATH_SEPARATOR=$lp_terminal_format
LP_COLOR_PATH_SHORTENED=$lp_terminal_format
lp_terminal_format -1 -1 1 0
LP_COLOR_PATH_LAST_DIR=$lp_terminal_format
LP_COLOR_PATH_VCS_ROOT=$lp_terminal_format
```

**Comment by LudovicRousseau** [comment]
This configuration is acceptable in both light and dark modes.
![light](https://user-images.githubusercontent.com/398496/107153275-ea1bb180-696c-11eb-982b-774339665278.png)
![dark](https://user-images.githubusercontent.com/398496/107153301-0d466100-696d-11eb-8f1f-4c08bd947dfa.png)

Good job. I am happy with this default configuration.

**Comment by Rycieos** [comment]
How about these examples for the documentation on the `lp_terminal_format()` function?

```rst
   For example, to set the error color to a bright, bold pink, with a fallback
   color of red::

      lp_terminal_format 204 -1 1 0 1
      LP_COLOR_ERR=$lp_terminal_format

   To set the prompt mark color to black on a white background::

      lp_terminal_format 0 7
      LP_COLOR_MARK=$lp_terminal_format
```

**Comment by LudovicRousseau** [comment]
OK for the new documentation.

**Comment by Rycieos** [comment]
Ok, I'll merge a commit with the defaults changes in a moment.

**Comment by Rycieos** [comment]
I've merged fixes for this and #656 in ae71304abcdcbbaff536ae42d3d43bbf4a35079b, could you test that commit to double check before I make a release on it?

**Comment by LudovicRousseau** [comment]
It is OK. Go for the release.

**Comment by Rycieos** [comment]
[v2.0.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.1) released. Thanks for the report! And thanks for working to convince me what the right solution was.
