### ISSUE TITLE
git prompt broken for worktrees in v2.0

### ISSUE THREAD

**Issue by andreimatei** [nojhan/liquidprompt#658]
I used to get the git prompt when I was in a worktree dir (`git worktree`). Not any more; now it's as if I'm not inside a repo dir. 
I've bisected to https://github.com/nojhan/liquidprompt/commit/f434b6dc663d704e9d616b8864908371862b9e23

FWIW, `git rev-parse --is-inside-work-tree` properly detects the worktree.
It's easy to reproduce by creating a worktree (`git worktree add <path>; cd <path>`).

Thanks!

**Comment by Rycieos** [comment]
I'm currently on vacation, so responses might be slow.

Thanks for the clear report, and stupid simple reproduction steps.

Yeah, this one is a bit embarrassing. I have always wanted to use workdirs more often, but have been too lazy to really learn how they work. As a self proclamed Git expert, I really should have already known.

Anyway, good bisecting work. That commit moved away from using that 'is-work-tree' command all the time to determine if the current directory is a Git dir to instead looking for a '.git/' directory, since it is so much faster. But a workdir uses a '.git' file, so that match failed.

I pushed the above commit to add a check for that. Could you give it a test?

**Comment by Rycieos** [comment]
@andreimatei any chance to test commit fc44d9724127e6b3bd803be5afed45d64fa566e4?

**Comment by andreimatei** [comment]
Sorry for missing you previous message. The commit works.
Thanks!

**Comment by Rycieos** [comment]
Fix released as part of [v2.0.2](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.2).
