### ISSUE TITLE
Re-license as GPL (instead of current Affero-GPL)

### ISSUE THREAD

**Issue by ottok** [nojhan/liquidprompt#675]
This project is currently licensed as Affero-GPL. That license is intended for web software and mandates that if the software is provided as a service, also the source code should be made available to the users.

This use case does not fit Liquid Prompt very well. Or in what situation did you envision that the Affero service clauses would be triggered?

There is a danger that inside many larger companies that are very diligent with IP issues anything licensed AGPL might be automatically discarded, and in the case of Liquid Prompt in vain (as it is now web software). I would argue that for Liquid Prompt it would be better to get more users and more exposure with a slightly less "enterprise risky" license than with current AGPL.

Therefore I propose that project to be re-licensed as GPL v2 (or v3, but again the less "enterprise risky" version is v2). A re-licensing process is not easy and can take years, depending on how many contributors made _non-trivial_ contributions. But it would be worth it. So better start now :)

**Comment by Rycieos** [comment]
I will agree that the Affero license seems an odd choice. I don't know why @nojhan chose that when he started the project, maybe he can shed some light on that.

The licenses are almost identical; here is the main section that the Affero version adds:

 > Notwithstanding any other provision of this License, if you modify the
> Program, your modified version must prominently offer all users
> interacting with it remotely through a computer network (if your version
> supports such interaction) an opportunity to receive the Corresponding
> Source of your version by providing access to the Corresponding Source
> from a network server at no charge, through some standard or customary
> means of facilitating copying of software.  This Corresponding Source
> shall include the Corresponding Source for any work covered by version 3
> of the GNU General Public License that is incorporated pursuant to the
> following paragraph.

I am not a lawyer, but by my understanding:

1. Since Liquidprompt does not work that way ("over a computer network"), this section does not apply.
2. Even if it did, since the only way to run Shell code is to load the source code, anyone using Liquidprompt has already downloaded the source anyway.

Therefore, I don't see any difference if we were to change licenses. And it would be a large amount of work to make it happen. But I'll leave this open for discussion.

**Comment by nojhan** [comment]
First, I disagree that the AGPL would only apply to the Web. The Affero clause is quite clear that it targets any kind of SaaS over a network, which is exactly the case if you use LiquidPrompt over an SSH connection, for instance. LiquidPrompt does provide the service of an (sometimes even interactive) prompt, that may even be used across a network. By interacting with LP over SSH, you are very clearly under the Affero clause. Think about it, what is different than an interaction with web server? You're sending data through a network protocol and you get data in return. It's a very common interpretation of the AGPL.

Having worked at a large, free software averse, company for the past 20 years, I'm very well aware of the consequences of a libre software license rather than a permissive open-source one (both pros and cons, I would say, as there is a lot of disadvantages of permissive licenses, too). However, I have to point out that the only thing that the AGPL demands, is to give (and allow the sharing of) the LP operating source code.

As for this copyleft clause of the GPL license family, I see no common use-cases in which it would be of the utmost necessity. LP is not a framework to make [proprietary] software with, it's really a ready-to-use service. An enterprise thus takes zero risk at using it, as it is very probably not a part of a larger third party software.

As for the v2 VS v3, I recall that versions 3 are protection against patent trolling, not good faith enterprise averse clauses. The rationale here is the same than the source-code availability. In the case someone would let you use LP, it's not because you would have access to the source code that you would be allowed to actually copy it (that's the rationale for copyleft). In the same way, that's not because you would be able to copy the source code that you would be allowed to operate it freely if it is patented (that's the rationale for version 3 clauses). Here again, a company that would not be patent trolling would just have to indicate that its modified LP version is already available in the operated shell. I think it's safe to say that it's not a big obstacle.

All in all, the AGPL allows to protect this free software from the major strategies of source code privation, at the cost of a very negligible effort from the operator, and no major impact on a (still to be defined) derivated business model. I thus see no point for a re-licensing.

Finally, a re-licensing may be very well very hard to conduct, given the number of contributors you would have to convince. As of now, I'm not convinced at all, for instance :-)

**Comment by ottok** [comment]
Thanks for the background! I will try to submit a PR that extends the README to include the main points of above so other people who wonder about the topic can read the reasoning directly.

**Comment by nojhan** [comment]
That's actually a very good idea! Many thanks.
