### ISSUE TITLE
python virtual env not deactivatable in zsh

### ISSUE THREAD

**Issue by micgro42** [nojhan/liquidprompt#676]
Shell: zsh 5.8
Operating system: Linux 5.11.0-18-generic Ubuntu 21.04
Liquidprompt version: f0442e87744671a70fa4fefd552b1750cc8a3b0b (i.e. current master)

### Steps to Reproduce
1. in `.zshrc` configure and load liquidprompt like that:
![image](https://user-images.githubusercontent.com/7372507/122034476-da582200-cdd1-11eb-9d53-fc4338f7e7fe.png)

2. open a new shell
3.

### Expected Behavior
No cyan section (presumably showing the virtual env) is ever visible

### Current Behavior
![image](https://user-images.githubusercontent.com/7372507/122040929-b0562e00-cdd8-11eb-97a7-28b2b856570c.png)

It is especially annoying since it only ever shows `[system]` as I not even working with python :/

### Possible Solution
:shrug: 

### Note

Please note that the dirstack works. So that configuration is working in principle.

**Comment by Rycieos** [comment]
Python virtualenv is not the only thing displayed after the main block but before the VCS block. There have been quite a few recent merged PRs that have added new sections; see the [Default theme template sections](https://liquidprompt.readthedocs.io/en/latest/theme/default.html#LP_SCLS) part of the documentation. (Though those docs seem to be missing the `LP_RUBY_VENV` section, something to be fixed before v2.1 release. I'll add a commit in a second.)

As you seem to have noticed, the Software Collections section uses the same coloring as the Python virtualenv section. Ruby venv also uses the same `LP_COLOR_VIRTUALENV`, and Kubecontext uses `LP_COLOR_KUBECONTEXT`, which also defaults to Cyan.

Since the string you see is "system", I am quite sure what you are seeing is a Ruby virtualenv. You must have either `rvm-prompt` or `rbenv` installed. If you don't want to see that section, you can disable it with [`LP_ENABLE_RUBY_VENV`](https://liquidprompt.readthedocs.io/en/latest/config.html#LP_ENABLE_RUBY_VENV).

**Comment by micgro42** [comment]
Yes, it was the ruby environment indeed! Thank you for updating the documentation!
