### ISSUE TITLE
improve handling of PROMPT_COMMAND for newer bash & vte "API" (the term is being used very liberally here)

### ISSUE THREAD

**Issue by dreamcat4** [nojhan/liquidprompt#684]
### Description

It seems that at some point in recent months bash finally has now permitted arrays for `PROMPT_COMMAND` variable. So instead of it only being capable of accepting 1 function, it can now accept an array of functions. This should be a great improvement in being able to inter-operate alongside other existing mechanisms. the VTE feature is one such system that is important in most systems. As critically it is needed to remember the CWD / PWD when spawning new tabs or windows in the terminal program.

### How will this be useful?

By adding support for bash array, it will greatly simplify the previous workaround. And make the whole thing less buggy, cumbersome etc. The details of the previous workaround were also incredibly difficult for many people to actually get working and understand. So by adding this capability it brings liquidprompt up to date, and in parity with newer releases of bash. Which now enable this simpler method.

### Considerations

It seems like we need to add a little bit of extra code. To dynamically check the bash version. And see if the bash is capable of passing `PROMPT_COMMAND` as an array. (and preserving it as an array). Perhaps another checking is to first see if prompt command is a regular string, or an array. To know how to deal with it.

The current behavior on master branch seems to just overwrite it as a variable? Although IDK what happens in bash here if the variable is already an array. Maybe then it only overwrites the first element of the array. And is kept as an array. Sorry my bash is not that great without having to refer to the documentation and run some tests.

### Why do it?

Well... because after some consideration it would seem best for everybody. Given how great this prompt is, and also how broad the benefits are to so many other people

### Who do it?

    If you don't like this suggestion and prefer to keep only the current existing behaviour without any further changes...
        please say so

    If you do like this change but prefer to make the changes yourself
        Please say so

    If you do like this change and would prefer to do it but just don't know how to make the time for it
        Please say so

And we can proceed accordingly. Many thanks

**Comment by dreamcat4** [comment]
for reference, where this change is coming from:

https://gitlab.gnome.org/GNOME/vte/-/issues/37#note_1270465

> to fix the issue, the distribution needs to set up PROMPT_COMMAND as an array before vte.sh is sourced, and make sure no other profile.d script overwrites it with a string

to append the extra shell function `__vte_osc7` from `/etc/profile.d/vte.sh`. This then gets the VTE to work. Previously I had to create a wrapper function. But the for doing that code was re-entrant (and very obtuse). And just plain bad. Getting rid of it would be much cleaner and better for everybody out there. The proposed change it's surely a good thing

**Comment by Rycieos** [comment]
First, this array `PROMPT_COMMAND` feature was added less than a year ago in Bash 5.1 (specifically [bash-5.1-alpha](https://github.com/bminor/bash/blob/ce23728687ce9e584333367075c9deef413553fa/CHANGES#L566-L567)). This is the latest version of Bash, which isn't a problem itself, but we support Bash back to version 3.2.

While we _could_ add special logic handle Bash 5.1+ specially and handle the `PROMPT_COMMAND` variable as an array, it would add a lot of complexity, we would need custom handling in all of these places:
https://github.com/nojhan/liquidprompt/blob/97f6bfadcf0048fc7b5bbdbeabec238756df2c71/liquidprompt#L2974-L2975
https://github.com/nojhan/liquidprompt/blob/97f6bfadcf0048fc7b5bbdbeabec238756df2c71/liquidprompt#L3066-L3070
https://github.com/nojhan/liquidprompt/blob/97f6bfadcf0048fc7b5bbdbeabec238756df2c71/liquidprompt#L3170-L3171

But

> > make sure no other profile.d script overwrites it with a string

This is a good point. No one has reported an issue until now about this, so I guess either no one is using Bash 5.1, or no one has bothered to convert their `PROMPT_COMMAND` usage to array syntax. Anyway, **we should support this somehow**. Hopefully the recent work in 0ce764653a5f000598b6ad11c974fcefb65832da and 840166f7a0396d9c942f50d1d7906edbc360f285 will make this easier.

There is at least some good news: it seems that every element in the array gets the value of `$?` set correctly (unlike a string version of `PROMPT_COMMAND`, which only the first statement run gets it, since the others take up the exit code of the first statement):
```bash
$ func1() { : ; }
$ func2() { echo "$?"; }
$ PROMPT_COMMAND=( func1 func2 )
0
$ false
1
```

So we wouldn't need to worry about making sure we were executed first in that case.

The biggest issue would be figuring out which way the `PROMPT_COMMAND` is being used. Turns out it is _really_ hard to test in Bash if a variable is a string or an array. Ideally we would depend on the user to set it for us, but if they don't, the variable just doesn't exist at all, and then which do we pick? Any scripts loaded later might assume the old way or like the one you linked, the new way. I don't see a good way to do it.

I hate half baked solutions, so I won't be merging anything yet. I welcome discussion or PRs on ways to implement this.

**Comment by Rycieos** [comment]
I took another look at this and tried a small change in 3553a658931091813b9e7d1e3824ddb8719ea5ea to resolve this. Please test and let me know how it works.

**Comment by dreamcat4** [comment]
It works, the specifics are in the other issue as: **`Test 3`** and **`Test 4`**
