### ISSUE TITLE
Execution time digits of precision

### ISSUE THREAD

**Issue by jhgorse** [nojhan/liquidprompt#691]
Sometimes the time of execution of last command has way too many digits of precision.

Shell: zsh 5.8

Operating system: Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

Liquidprompt version: v2.0.3

### Steps to Reproduce

1. Use Liquidprompt v2.0.3 via zinit on latest macOS and it happens on occasion.

My feeble attempts to reproduce regularly have so far failed.

### Expected Behavior

Stop at 3rd significant digit.
`9.17m10.s`

### Current Behavior

![image](https://user-images.githubusercontent.com/1783474/146691348-d3db7a94-cfd1-4176-bffc-1d4f66ed6060.png)
`9.1666666666666661m10.s`

**Comment by Rycieos** [comment]
Must be a weird quirk of how zsh does modulus math. Can you please post your zsh version? I'll try to reproduce this.

**Comment by Rycieos** [comment]
I can't reproduce this with the following shells:
* zsh 5.0.8 (x86_64-unknown-linux-gnu)
* zsh 5.1.1 (x86_64-unknown-linux-gnu)
* zsh 5.2 (x86_64-unknown-linux-gnu)
* zsh 5.3.1 (x86_64-unknown-linux-gnu)
* zsh 5.4.2 (x86_64-unknown-linux-gnu)
* zsh 5.5.1 (x86_64-redhat-linux-gnu)
* zsh 5.8 (x86_64-pc-linux-gnu)
* zsh 5.8 (x86_64-apple-darwin21.0)

Reproduction attempt:
```
% __lp_runtime_after() { _LP_RUNTIME_SECONDS=550; }
[mark@jaguar:~] 9m10s %
```

You wouldn't have happened to change the type of `SECONDS` to a float? From the man page:
> SECONDS \<S>
The number of seconds since shell invocation.  If this parameter is assigned a value, then the value returned upon reference will be the value that was assigned plus the number of seconds since the assignment.
> 
> Unlike other special parameters, the type of the SECONDS parameter can be changed using the typeset command.  Only integer and one of the floating  point  types are  allowed.   For  example,  `typeset -F SECONDS` causes the value to be reported as a floating point number.  The value is available to microsecond accuracy, although the shell may show more or fewer digits depending on the use of typeset.  See the documentation for the builtin  typeset  in  `zshbuiltins(1)`  for  more details.

What does this output for you?
```
% typeset -p SECONDS
typeset -i10 SECONDS=474
```
The default seems to be integer, not float.

Can you post some debug output as well as your zsh version? Try this:
```
% echo "$((70 % 60))"
% __lp_runtime_after() { _LP_RUNTIME_SECONDS=550; }
% set -x
```

**Comment by jhgorse** [comment]
You may need the latest Darwin:
```
> echo $ZSH_VERSION
5.8
> uname -v
Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
```

```
[jhg:~] 9.1666666666666661m10.s 1 % typeset -p SECONDS
typeset -i10 SECONDS=74
```

Successful reproduction in my env:
```
[jhg:~] % __lp_runtime_after() { _LP_RUNTIME_SECONDS=550; }
[jhg:~] 9.1666666666666661m10.s %
```

Cheers,
Joe

**Comment by Rycieos** [comment]
I just updated my MacBook to test this, and no change:
```
% uname -v
Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
% zsh --version
zsh 5.8 (x86_64-apple-darwin21.0)
% __lp_runtime_after() { _LP_RUNTIME_SECONDS=550; }
⌁49% [mark:~/dev/liquidprompt] master 9m10s 
```

I'm running zsh with no config file, can you also try the same? The only difference I see between our setups is that your machine is ARM64 and mine is x86_64, which really should not affect what type the `SECONDS` special variable is.

**Comment by jhgorse** [comment]
You are right. It was zinit.

Bad zinit.
