### ISSUE TITLE
Some prompt themes not showing/working

### ISSUE THREAD

**Issue by ZWORX52** [nojhan/liquidprompt#698]
I am using Liquidprompt and would like to use the alternate-vcs theme. I have it installed on Ubuntu 64-bit 21.10 (GNOME 40.4.0 if that matters) and am using the default terminal.

I am running the commands below, as per the wiki on "switching themes" but they have no effect. The root user, for some reason, has the alternate-vcs theme installed and working (by default).
```bash
source ~/liquidprompt/themes/alternate_vcs/alternate_vcs.theme
lp_theme --list  # The theme shows! Now to switch to it...
lp_theme alternate_vcs  # ... What? Nothing changed!
```
![image](https://user-images.githubusercontent.com/66217856/154763463-05a7ab95-90fc-43ed-a7e9-664df93759f2.png)

Running the same commands, but trying to use the powerline (or powerline-full) themes both work, however they are square (the wiki shows them as having triangles on the edges, also Ubuntu refuses to show some of the characters).
![image](https://user-images.githubusercontent.com/66217856/154763616-45cdbcc2-92af-49a7-a637-4ac7c33ec861.png)

Thanks in advance for your time.

**Comment by Rycieos** [comment]
You will want to check out the documentation for those themes:
https://liquidprompt.readthedocs.io/en/stable/theme/included/alternate_vcs.html
https://liquidprompt.readthedocs.io/en/stable/theme/included/powerline.html

Specifically, the section in Alternate VCS that says:
> The alternate_vcs theme is an extension of the default theme.

Usually the Alternate VCS theme looks exactly the same as the default theme. It only looks different when showing VCS parts of the prompt. Try `cd`ing to a VCS directory and you should see the differences.

And for Powerline, see the section called [Setup](https://liquidprompt.readthedocs.io/en/stable/theme/included/powerline.html#setup). You need to install a compatible font.

If there is anything in the documentation that isn't clear, please reply back so we can improve the documentation.

**Comment by ZWORX52** [comment]
As an aside, the alternate vcs theme images look nothing like the ones I am getting. Do I have the wrong version? Is there a theme I can get that looks like that (because that is what I want, for my user prompt to look like the root prompt)? And if the alternate_vcs is simply an extension, then why do the images on the wiki look so different from the prompts I am getting?

**Comment by Rycieos** [comment]
If you use the `tools/theme-previes.sh` script, it will show you how a theme is supposed to look. That is how the screenshots in the docs are generated. When I run that script, I see this:

![image](https://user-images.githubusercontent.com/8375571/154776507-97f814b4-ce71-44fb-9eb8-27451cb8e05e.png)

If you see something different when running that script, that is probably a bug, since the script keeps the prompt configuration the same for everyone so it can function as a good preview.

If you are seeing something different in your actual prompt than what the preview is showing, you probably have a different configuration. Try using a default configuration for Liquidprompt and seeing if that brings it in line. If that still doesn't work, then either you have something else weird in your shell configuration, or there is a bug in Liquidprompt. I can try to help you track that down: post the contents of your Liquidprompt config, and `printf '%q\n' "$PS1"`.

**Comment by ZWORX52** [comment]
I have not touched the config. I will send it anyway. (Here: [liquidpromptrc](https://github.com/nojhan/liquidprompt/files/8102433/liquidpromptrc.txt)) Output of the printf command: `$'\\u\\[\E(B\E[m\\]\\[\E[32m\\]@\\h\\[\E(B\E[m\\]\\[\E[32m\\]:\\[\E(B\E[m\\]\\[\E[1m\\]~\\[\E(B\E[m\E[90m\\]/\\[\E(B\E[m\E[1m\\]liquidprompt\\[\E(B\E[m\\] \\[\E[32m\\]stable\\[\E(B\E[m\\] \\[\E[1m\\]±\\[\E(B\E[m\\] '` Screenshots of me running the theme-previews.sh script:
![image](https://user-images.githubusercontent.com/66217856/154806471-0813f751-2662-4014-9994-09b1f790459b.png)
(Note that my prompt is totally different from the displayed one)
As a few more asides, I do not have `PROMPT_COMMAND` set in my .bashrc. I installed first via apt-get but then used the github version because I was confused how my prompt didn't look too different. I don't think it should be a problem, but I did use `sudo apt-get remove liquidprompt` to check that I do indeed only have the github installation.

**Comment by ZWORX52** [comment]
A note: I mentioned in the original post, that it works for the ROOT user. 
![image](https://user-images.githubusercontent.com/66217856/154807309-56aa3824-dfe0-47ab-b7a7-d163144dc325.png)
Here is a screenshot of that working.

**Comment by ZWORX52** [comment]
For some reason, now when I open a new terminal the following things happen:
```
bash: /usr/share/liquidprompt/debian.theme: No such file or directory
[zworx52@ubuntu:~] $
```
(Read: liquidprompt erroring and failing to display the default prompt)

**Comment by ZWORX52** [comment]
My terminal seems to be pretty messed up. I tried a few things (namely reinstalling a few times) and now a lot of bad things happen when I open a new terminal.
![image](https://user-images.githubusercontent.com/66217856/154810631-5e30f9d8-9ed8-4d42-b56b-d854e824cb34.png)

**Comment by Rycieos** [comment]
> I have not touched the config. Here:

The config you are running is the default config from the v_1.11 tag, modified by the Debian package maintainer.

You haven't mentioned what version of Liquidprompt you are running. If you are running it from a Git clone, `stable` branch (like your screenshots suggest), then this config will work, but is missing some features (and has some deprecated defaults).

If you had Liquidprompt installed from the Ubuntu package, then that version is still 1.11, which is five and a half years old! Note that I don't maintain the packages of Liquidprompt, I have wonderful people who do that for Debian and Homebrew (but not Ubuntu).

I would highly recommend *not* to install Liquidprompt through `apt` on Ubuntu. Use Git to install it (like it seems you have done), and copy over your config with the dist version. Or, what I recommend is to make your config a blank file and only add options as you want to change the defaults. That's what I do for [my config](https://github.com/Rycieos/dot-files/blob/master/liquidprompt/config).

As for why you aren't seeing the prompt: it obviously isn't installed right. The PS1 output you sent is not one that Liquidprompt would generate, so something else is making that. Probably the Ubuntu default PS1. Look over the [install docs](https://liquidprompt.readthedocs.io/en/stable/install.html#shell-installation) again, make sure you have the section in your `.bashrc` or `.zshrc`. If you ran the `liquidprompt_activate` script that came with the `apt` package, it will have included a bunch of lines in those files, and you will need to remove them, since they only work for the package version. If you ran it multiple times, they will be in there multiple times.

If you still can't get it to work correctly, upload your shell config file, and I'll take a look.

**Comment by ZWORX52** [comment]
I figured it out, all I needed to do was `sudo apt-get purge liquidprompt` and then re-source the `~/liquidprompt/liquidprompt` file again. Thanks for your time, this was an annoying problem. Sorry I didn't figure this out earlier! Again, many thanks. :heart:
