### ISSUE TITLE
liquidprompt does not recognize git directory

### ISSUE THREAD

**Issue by chrisdane** [nojhan/liquidprompt#699]
Hi

On computer1, liquidprompt works as expected: after `cd`ing from a non-git to a git directory the prompt changes by showing a short version of `git status` in form of the branch name and current diffs either in green (no diffs) or red (some diffs).

On computer2, after `cd`ing into the same git directory, liquidprompt does not recognize that this directory actually is a git directory. The prompt does not change from the default non-git-directory style. Explicitly typing `git status`, however, confirms that I am in a git repository. Liquidprompt shows this behavior in all git directories on computer2.

What could be missing/wrong on computer2? 

Thanks a lot for any help and kind regards,
Chris

Shell: 
```
echo $BASH_VERSION
4.4.19(1)-release
```

Operating system:
```
cat /etc/*release
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"
Red Hat Enterprise Linux release 8.4 (Ootpa)
Red Hat Enterprise Linux release 8.4 (Ootpa)
```
```
cat /proc/version
Linux version 4.18.0-305.25.1.el8_4.x86_64 (mockbuild@x86-vm-09.build.eng.bos.redhat.com) (gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)) #1 SMP Mon Oct 18 14:34:11 EDT 2021
```

Liquidprompt version: 
```
git describe --tags --exact-match
fatal: no tag exactly matches '83d98f0d5a79f812257c1b17af2262460a6f7a3b'
```
```
git rev-parse HEAD
83d98f0d5a79f812257c1b17af2262460a6f7a3b
```
### Steps to Reproduce

1. First sentence above
2. Second sentence above

### Expected Behavior

That liquidprompt works on computerX as on computer1 for X in 2 to n.

### Current Behavior

Second sentence above

**Comment by Rycieos** [comment]
There are a few reasons Liquidprompt could be not discovering a Git repo. Liquidprompt "cheats" by doing a quick check manually instead of calling `git status`. You can run `[[ -d ./.git || -f ./.git ]] && echo "git dir"` to approximate that. If your Git repo doesn't pass that test, then something is very weird with it.

More likely, you have disabled Git in Liquidprompt. You can test this by `echo "$LP_ENABLE_GIT"`. `1` is enabled, `0` is not. Check your Liquidprompt config if you have it disabled there. It could also be disabled if you don't have a `git` binary on your path, though it seems that you do.

Lastly, the config option [`LP_DISABLED_VCS_PATHS`](https://liquidprompt.readthedocs.io/en/stable/config.html#LP_DISABLED_VCS_PATHS) can cause this. Check that you aren't setting it, or that it wasn't set somehow (`printf '%s\n' "${LP_DISABLED_VCS_PATHS[@]}"`). The deprecated option [`LP_DISABLED_VCS_PATH`](https://liquidprompt.readthedocs.io/en/stable/config.html#LP_DISABLED_VCS_PATH) can set the former option, so if you can't figure out how it got set, check for that too.

**Comment by chrisdane** [comment]
Thanks a lot, you solved it!

On login to computer2, git is not available by default, but needs to get loaded via `module load git` (this is often the case on some remote servers/super computers/etc.). In my .bashrc, liquidprompt is loaded before I load git, which is why `LP_ENABLE_GIT` was set `0`. Loading git before sourcing liquidprompt in the .bashrc solves this.

Thanks a lot and cheers,
Chris
