### ISSUE TITLE
Getting error: bash: /usr/share/liquidprompt/debian.theme: No such file or directory

### ISSUE THREAD

**Issue by ZWORX52** [nojhan/liquidprompt#700]
Shell: `"bash 5.1.8(1)-release"`

Operating system: `Linux ubuntu 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Liquidprompt version: `83d98f0d5a79f812257c1b17af2262460a6f7a3b` (output from `git rev-parse HEAD` command, git describe --tags --exact-match responded with this (in the cloned directory): `fatal: no tag exactly matches '83d98f0d5a79f812257c1b17af2262460a6f7a3b'`)

### Steps to Reproduce

1. `git clone --branch master https://github.com/nojhan/liquidprompt.git ~/liquidprompt`
2. `source ~/liquidprompt/liquidprompt`

### Expected Behavior

Liquidprompt gets installed and adds itself to ~/.bashrc.

### Current Behavior

The sourcing of the script crashes and no installation happens.

### Possible Solution

A temporary solution would be to put `source ~/liquidprompt/liquidprompt` in the .bashrc because it activates, it just doesn't install fully (and maybe some things are missing).

**Comment by Rycieos** [comment]
> Expected Behavior: Liquidprompt gets installed and adds itself to ~/.bashrc.

This is not expected behavior. Liquidprompt does not install itself, as it has no way of being intelligent enough to know where in your RC file to put the source statement. See the [installation docs](https://liquidprompt.readthedocs.io/en/stable/install.html#shell-installation), you must add those lines yourself. (Note that the Debian package does include a way to auto-install into your RC file, but you still need to run a command, and it sometimes puts the lines in the wrong place, or even worse, multiple times if you run the install command more than once.)

As for the other issue, I think it's a leftover from your #698. Since you purged the `apt` package, that file no longer exists (`/usr/share/liquidprompt/debian.theme` is a file only included in the Debian package). There is only so much I can help with, since that file is not a part of this project. I am guessing that you still are using the config template that came with that package. You probably have a line that looks like
```
LP_PS1_FILE=/usr/share/liquidprompt/debian.theme
```
in there. Remove that, or as I suggested before, empty your whole config and only add options you want to change from the defaults.

**Comment by ZWORX52** [comment]
Sorry for taking up so much of your time. You've been a great help and it's a great app. Thanks so much!
