### ISSUE TITLE
Add an option to customize the mercurial binary

### ISSUE THREAD

**Issue by azmeuk** [nojhan/liquidprompt#701]
This issue is related to #680

I just discovered that mercurial ships the [chg](https://www.mercurial-scm.org/wiki/CHg) binary that runs a mercurial agent to speed up mercurial commands. The performance difference is really significative in a prompt context. There is also the upcoming rust-written [rhg](https://www.mercurial-scm.org/repo/hg/file/tip/rust/README.rst) binary that promise good performances as well.

In order to use one of those binaries with liquidprompt, I would love if liquidprompt had an option where one could customize the mercurial binary to use.

What do you think?

**Comment by Rycieos** [comment]
I think that is fantastic news for Mercurial.

This is something I have already run into with Bazaar, with its replacement project [Breezy](https://www.breezy-vcs.org/) (binary name `brz`).

I added [a suggestion to our documentation for Bazaar showing how to remap with a function](https://liquidprompt.readthedocs.io/en/stable/functions/data/vcs.html#bazaar). Using a function works when an alias does not because of how shells treat the escaped version of a binary evocation: `\hg status`. That will bypass aliases, but not functions.

I see 2 options:
1. Add a `LP_HG_BINARY` config option.
2. Suggest that users map the tool of their choice to `hg`. Either with:
  a. A function: `hg() { chg "$@"; }`
  b. A symlink: `ln -s /usr/bin/chg /usr/local/bin/hg`

My concern with the first option is that we should obviously add such an option for Bazaar as well. But where do we stop? Do we add binary configurations for all our VCS providers? What about all the other tools we use, like `sensors` or even `grep`?

I am not saying your suggestion is bad; far from it. I want to hear some discussion on this, see if anyone else wants such an option.

**Comment by azmeuk** [comment]
The main drawback I can think of by overriding `hg` with a function is that is global, but one may want to use `chg` or `rhg` in the prompt, but stay with `hg` in the shell.

As `rhg` is a rust rewrite of hg, it is far from having reached feature equality with `hg`, and there might be a point (not yet) where `rhg` would be good enough for prompt display, but would not have enough feature implemented to be a full replacement of `hg`. I don't really know about integration with extensions and `rhg` neither.

**Comment by Rycieos** [comment]
That is a valid use case. What does `rhg` do if you use a subcommand that it doesn't support? I would hope it would error, and then Liquidprompt would think there is no data and not show that bit.

Would you think any other tools should have a way to change what binary they call?

**Comment by azmeuk** [comment]
> That is a valid use case. What does `rhg` do if you use a subcommand that it doesn't support? I would hope it would error, and then Liquidprompt would think there is no data and not show that bit.

There are several behaviors users can configure. Basically either stop or fall back to hg. I don't know if this applies to subcommand options too though (for instance does rhg fallback to hg if `rhg subcommand --foobar` option is not implemented yet?)

> Would you think any other tools should have a way to change what binary they call?

I think this would be ok for a project like liquidprompt to have configuration options to customize the binaries. However I understand the additional work needed to implement all of those options, while this does not feel needed yet. I would suggest implementing such an option for mercurial only, and wait for people asking for other tool binary customization options before implementing them.

**Comment by Rycieos** [comment]
I've added a config option (`LP_HG_COMMAND`) for this, as it was simple enough to do.

**Comment by azmeuk** [comment]
Thank you so much!
:heart:
