### ISSUE TITLE
Support for systemd-nspawn containers

### ISSUE THREAD

**Issue by rfc1036** [nojhan/liquidprompt#709]
Detection of `systemd-nspawn` containers can be supported by adding to the bottom of `_lp_container()` something like:

```
  ...
  elif [[ -e /run/host/container-manager ]]; then
    local lp_container="$(< /run/host/container-manager)"
    lp_container="${lp_container#systemd-}"
  else
  ...
```

This API is documented in https://systemd.io/CONTAINER_INTERFACE/ .

**Comment by Rycieos** [comment]
The link you sent is documentation for the systemd chunk inside of the container. systemd-nspawn is the container runtime; the service outside of the container, which is what we want to detect. It would make sense however that systemd-nspawn would follow the API that systemd documents.

I could not find any docs for systemd-npawn on this file API, but I did find the source code:
https://github.com/systemd/systemd/blob/27408ef8780cdfb66c297a988d5945ec7a4b5837/src/nspawn/nspawn.c#L206
https://github.com/systemd/systemd/blob/27408ef8780cdfb66c297a988d5945ec7a4b5837/src/nspawn/nspawn.c#L3958-L3959

It seems that by default that file is populated with the string `systemd-nspawn`.

The only question left is what priority to give this detection? I would say to check it last, since if, for example, the container is a systemd enabled image running inside Docker, this file would still exist (probably with the string "docker", admittedly), but we still want to detect Docker first.

**Comment by rfc1036** [comment]
Indeed I suggested that this code should be at the bottom of the function (last).
I do not think that the file can contain anything other than "systemd-nspawn"' at this point, but I tried to write generic code.
