### ISSUE TITLE
Slowdown with enabled git fsmonitor (since git 2.37.0)

### ISSUE THREAD

**Issue by kmARC** [nojhan/liquidprompt#717]
When git [`core.fsmonitor`](https://www.git-scm.com/docs/git-config#Documentation/git-config.txt-corefsmonitor) is enabled, liquidprompt displays very slowly.

It seems to be it spends time on `git diff --shortstat HEAD`:

```bash
± time git --no-pager diff --shortstat HEAD 2>/dev/null
 21905 files changed, 2494869 deletions(-)

real    0m1.372s
user    0m0.392s
sys     0m0.634s
``` 

Switching fsmonitor off, or removing `HEAD` from the command line argument both speeds up operation:

```bash
± time git --no-pager -c core.fsmonitor=false diff --shortstat HEAD 2>/dev/null

real    0m0.132s
user    0m0.038s
sys     0m0.776s

± time git --no-pager diff --shortstat 2>/dev/null

real    0m0.055s
user    0m0.014s
sys     0m0.014s 
```

Shell: `5.1.16(1)-release`

Operating system: `Darwin Laptop056 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64 arm Darwin`

Liquidprompt version: `/opt/homebrew/Cellar/liquidprompt/2.1.2 `

### Steps to Reproduce

1. Go to a large git repository's directory
2. Enable `core.fsmonitor`

### Expected Behavior
No slowdonws

### Current Behavior
As long as fsmonitor is enabled, it slows liquidprompt display significantly

### Possible Solution
Add `-c core.fsmonitor=false` to `_lp_git_diff_shortstat_uncommitted`

This might be an upstream bug? Since `git diff HEAD` would display all 2.5M lines of code deleted from the repository, whereas `git diff` doesn't show any changes.

```bash
± git --no-pager config -l
credential.helper=osxkeychain
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
core.fsmonitor=true
commit.gpgsign=false
remote.origin.url=...
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.qa.remote=origin
branch.qa.merge=refs/heads/qa
```

**Comment by Rycieos** [comment]
Thanks for testing this, it is something I was planning on doing when I saw Git 2.37 was released, but had not got around to it yet.

Interestingly, I do not have as poor performance losses as you do, even though we are on the same OS. Maybe the test repo I used is much different? (I simply ran `rm -r *` in my Liquidprompt repo to create many changes.)

Your suggestion of removing `HEAD` from the command arguments would not work, as that creates a different comparison:
* `diff`: compares working directory to staging
* `diff HEAD`: compares working directory to HEAD commit
* `diff --cached`: compares staging to HEAD commit

Liquidprompt actually supports and uses all three.

But I do see some performance losses on the `git diff` commands, though only slight. That is true for `git status` commands as well, which is where the FSmonitor daemon is supposed to shine. Seems to me like this feature isn't performance ready yet, at least on arm64 Darwin.

I took a quick scan through the Git bug tracker, and didn't find any reports of poor performance like this. Might be worth your time to file a report, since your case is quite severe.

As for your suggested fix, I don't think that overriding config options at runtime is a good idea. We can't know if the performance gain you and I see would be the same for everyone else. I think the correct solution is to report upstream and wait for a fix. If upstream for some reason rejects a report, and we get more reports of situations where turning `core.fsmonitor=true` makes sense (which it does not for me, since it makes everything slower), but it slows down `diff`s, then we can reevaluate.

**Comment by kmARC** [comment]
Thanks for looking it to this. The repo I have to work with has millions of lines of code and it's running now on an M1 mac and I/O is jsut generally slow. Having this enabled on this particular repo sometimes causes 1-2 **seconds** until the prompt appear (after even pressing Return). 

I have to switch of fsmonitor otherwise the reported numbers are simply wrong too...

**Comment by Rycieos** [comment]
> I have to switch of fsmonitor otherwise the reported numbers are simply wrong too...

That's just plainly wrong. The feature should be drop in with no changes to functionality. You should definitely report that to the Git maintainers. Unless it *is* a problem in Liquidprompt, but I don't see how that could possibly be the case.
