### ISSUE TITLE
Invalid shell nesting level

### ISSUE THREAD

**Issue by carbolymer** [nojhan/liquidprompt#718]
Shell nesting level is displaying incorrect value. For all shells spawned under X, `$SHLVL` starts at `2` where the true level is `1`. See below:
```
[carbolymer:~]└2 % echo $SHLVL
2
[carbolymer:~]└2 % pstree -s $$ | grep sh- -o | wc -l
1
[carbolymer:~]└2 % zsh
[carbolymer:~]└3 % echo $SHLVL
3
[carbolymer:~]└3 % pstree -s $$ | grep sh- -o | wc -l
2
[carbolymer:~]└3 % zsh
[carbolymer:~]└4 % echo $SHLVL
4
[carbolymer:~]└4 % pstree -s $$ | grep sh- -o | wc -l
3
[carbolymer:~]└4 % pstree -s $$              
systemd───login───startx───xinit───xfce4-session───xfsettingsd───xfce4-terminal───zsh───zsh───zsh───pstree
```

Related feature: https://github.com/nojhan/liquidprompt/issues/606
Reference: https://stackoverflow.com/a/47067793/1608594

**Comment by zyzzyxdonta** [comment]
Might this be because startx is a shell script? For me it looks like this and the shlvl is correct:
```
systemd──systemd──plasmashell──konsole──bash──pstree
```

**Comment by carbolymer** [comment]
That could be the case. Nonetheless, `pstree` seems to be more reliable than `$SHLVL`, quoting stackoverflow answer I linked:

>I've found the second way [with `pstree`] to be more robust than the first whose value was reset when using sudo or became unreliable with env -i.
>
>None of them can correctly deal with su.

**Comment by Rycieos** [comment]
Thanks for the report.

Unfortunately, `pstree` is not available on MacOS or Cygwin, and probably wouldn't be on *BSD either (I don't have one handy to test). Even if it was, changing a variable access to two binary calls would add extra slowdown to the prompt.

Bash and Zsh just dumbly increment `SHLVL` when they start. They never claimed to do anything more, so no one can fault them.

I think this is a problem with the OS. I can't know for sure since you didn't add your OS details. But it is tough to label this a "problem" anyway, since everything is working as intended. It's just that you (understandably) do not want it to function that way.

There is no way for Liquidprompt to detect this situation, and we can't use `pstree` because it isn't portable. If anyone has a way for Liquidprompt to solve this, I'm open to ideas.

But since you want a solution, I have these ideas:
1. Fix it in `startx`, or whichever process in the tree is a shell script. It should `unset SHLVL` or similar before starting its child processes. This could either be something you hack yourself, or report to X11 maintainers or the OS maintainers.
2. Detect this situation in your shell startup, and fix it. This chunk at the top of a `.zshrc` would probably work:
    ```bash
    pstree_context="$(pstree -s $$)"
    # Fix for first shell inside terminal having wrong SHLVL.
    if [[ $pstree_context == *"───xfce4-terminal───zsh───pstree" ]]; then
        SHLVL=1
    fi
    ```
