### ISSUE TITLE
Shell mark

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#725]
Display a character indicating the shell in use.

### Description

Since Liquidprompt supports Bash, Zsh (and Fish?), it should be able to indicate which one is currently in use.
Probably just a single letter would be sufficient.
The beginning of the prompt seems to me to be the best location.
Optionally display the (major?) version.

### How will this be useful?

When connecting to a remote host, shell may vary.

**Comment by Rycieos** [comment]
> and Fish?

Liquidprompt does not support Fish. Fish is quite different, and does not follow most of the POSIX shell stuff. I doubt it would be possible to make Liquidprompt support Fish.

Currently, Liquidprompt does indicate which shell is running. The default prompt marks are `$` for Bash, and `%` for Zsh. It has been this way for 10 years, since 34c8d901cee4297a2642ec202c478e9f60522bb8. I do not think changing this functionality now would be a good idea.

I suppose adding extra functionality would not hurt, but I would want to see a mockup or proposal. And that would be for the default theme. The data is already exposed (though admittedly not through a data function) for themes to use.

Would that be what you are looking for, a data function for themes to use to get the current shell?

**Comment by nojhan** [comment]
`_LP_SHELL_*` variables are sufficient to build up theme displaying the shell name, so I close this issue.
