### ISSUE TITLE
Give names/icons to standard exit codes

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#729]
Display a more readable name along with/instead of the exit code, when it is a standard one.

### Description

Standard exit codes are best known through their names, optionally display them next to the error code.
Optionally shorten those names as single characters/icons.

See: https://stackoverflow.com/questions/1101957/are-there-any-standard-exit-status-codes-in-linux

### How will this be useful?

Better understanding of what's going on by the user.

**Comment by Rycieos** [comment]
Interesting idea. I would find this useful.

I would be cautious though about attributing specific codes to specific strings. As many of the linked answers and comments have pointed out, there is no standard around error codes, only some repeated patterns.

The one thing that is for sure the same between Bash and Zsh is that they will show the exit code of a process killed by a signal as 128 + the signal code (probably because the kernel sets the exit code). However, you can make any program return that exit code as well (`bash -c 'exit 135'`, would look like `SIGBUS`), which could be quite confusing.

We would also need to look into how portable these signals are, and if all OSes set the exit code on exit from a signal.

I would at least be open to displaying the 31 basic signals if they turn out to be portable. Other codes, I would need to see some patterns shown in common programs. I would rather show no information for a code than the wrong one.

**Comment by nojhan** [comment]
Done in #745
