### ISSUE TITLE
With Python Poetry, prompt shows literal "prompt = "

### ISSUE THREAD

**Issue by zyzzyxdonta** [nojhan/liquidprompt#760]
With [Poetry](https://python-poetry.org/), instead of showing only the prompt name given in pyvenv.cfg, the leading `prompt = ` is also shown in the prompt.

Shell: bash 5.2.12(1)-release

Operating system: Darwin ... 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

Liquid Prompt version: 74b775f2c42845c1e2e9468269013042ea436d39

### Steps to Reproduce

1. Install Poetry
2. Create Poetry project: `cd $(mktemp -d) && poetry init -n`
3. Open Poetry shell: `poetry shell`

### Expected Behavior

Prompt looks something like:
```
... └2 <tmp-kwfcoayq-py3.11> $
```

### Current Behavior

Prompt looks something like:
```
... └2 <prompt = tmp-kwfcoayq-py3.11> $
```

### ~~Possible Solution~~ Observation

`poetry env info` shows the path to the venv. The pyvenv.cfg inside it looks something like this:

```
virtualenv = 20.17.0
include-system-site-packages = false
base-prefix = /usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11
base-exec-prefix = /usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11
base-executable = /usr/local/opt/python@3.11/bin/python3.11
prompt = tmp-kwfcoayq-py3.11
```

After wrapping the string after `prompt =` in single quotes (as `python -m venv --prompt ...` would generate it), liquidprompt shows the expected result. I don't know if Poetry doesn't behave up to spec here or if it is fine to leave out the quotes.

**Comment by Rycieos** [comment]
Thanks for the report. I'll try to find a spec on this, but it's probably a case of no well defined spec.

**Comment by Rycieos** [comment]
Good reproduction steps, easy to reproduce.

The spec for `pyvenv.cfg` seems to be [PEP-405](https://peps.python.org/pep-0405/). It does not detail the file format other than to say
> ... this file is scanned for lines of the form `key = value`.

I think the actual file format is assumed to be an INI config file, and so this spec would apply:
https://docs.python.org/3/library/configparser.html#supported-ini-file-structure
This spec makes no mention of quoting values. And as there is no "global" spec for INI formats, this means I am right; the spec is very poorly defined. Not that is is actually true INI anyway; as it lacks a section header, `configparser` can't even read it!

I found the code where CPython's `venv` module creates the file: https://github.com/python/cpython/blob/v3.11.0/Lib/venv/__init__.py#L187. Note the `{var!r}` syntax, which uses `repr()`, which adds quotes around the value.
The trick is that for CPython, it never reads this file. It hardcodes values into the `activate` script so it doesn't need to read it. Poetry does the same thing actually.

Since it seems unreasonable to expect either CPython or Poetry to conform to a spec that doesn't really exist, I think this is something we will have to fix in Liquid Prompt.

**Comment by zyzzyxdonta** [comment]
Works perfectly. Thank you so much! 😄
