### ISSUE TITLE
Debugging prompt delay on default installation

### ISSUE THREAD

**Issue by kiteloopdesign** [nojhan/liquidprompt#764]
Default liquidprompt installation on bash shows a perceptible delay, even on folder where no git repo is present. I imagine this has to do with some setting that can be tweaked? However I do not know how to debug this, please help/

Shell name and version:  bash 5.1.8(1)-release

Operating system name and version.

Linux fedora 6.0.12-100.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 8 16:53:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
Fedora release 35 (Thirty Five)
NAME="Fedora Linux"
VERSION="35 (MATE-Compiz)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (MATE-Compiz)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="MATE-Compiz"
VARIANT_ID=matecompiz
Fedora release 35 (Thirty Five)
Fedora release 35 (Thirty Five)

```

Operating system: Fedora 35

Liquid Prompt version: v2.1.2

### Steps to Reproduce
Install liquidprompt. Source the liquidprompt file. Issue is visible on any folder, even those w/o git (which should render faster)

### Expected Behavior
Without any personalization prompt should be immediate

### Current Behavior
It takes several seconds to show the prompt

### Possible Solution
I don't know, is there any way to debug this? some log file to see what is lagging the prompt render?

**Comment by Rycieos** [comment]
You are correct, usually it is a specific tool that is slowing down the prompt. There is no built in system to make debugging this easy, as that itself would slow down the prompt. But, debugging isn't too hard manually.

First, run `LP_DEBUG_TIME=1 ; lp_activate` to enable printing the runtime before every prompt. This lets you see specific runtimes, and will let you observe what changes improve the time.

Next, run `declare -p | grep " LP_ENABLE"`, which will print every config option to enable or disable a feature, as well as its current setting (1 being enabled, 0 disabled). Start disabling specific features (eg, `LP_ENABLE_DETACHED_SESSIONS=0`), then running `lp_activate` after to reload the feature. Note that if you have that config option specified in your config file, `lp_activate` will load the option from the config file and will ignore your setting on the command line, so change it in your config file instead.

Keep disabling features until you find what makes a large change to your runtime. My guess as to what your issue is would be one of:
```
LP_ENABLE_DETACHED_SESSIONS
LP_ENABLE_JOBS
LP_ENABLE_LOAD
LP_ENABLE_TEMP
```

If you find the cause, you can try to read the source to find which command Liquid Prompt is running, and see if that command by itself is slow. For example, on my system, the `LP_ENABLE_DETACHED_SESSIONS` feature is quite slow, but that is because the `screen` tool is:
```bash
$ time screen -ls
No Sockets found in /run/screen/S-mark.

real   	0m0.050s
user   	0m0.013s
sys    	0m0.037s
```
If you find that Liquid Prompt itself is slow when the tool is not, then that's a bug we can try to fix.

**Comment by kiteloopdesign** [comment]
Wow, that was some quick reply, thanks so much!
So issue was indeed LP_ENABLE_TEMP, setting it to 0 fixes the issue
It would be good to have this included on the main page, I guess many people may have this issue?
Thanks!
